export interface AllahName {
  id: number;
  name: string;
  transliteration: string;
  meaning: string;
}

export const NAMES_OF_ALLAH: AllahName[] = [
  { id: 1, name: "Ar-Rahman", transliteration: "Ar-Rahmān", meaning: "The Most Gracious" },
  { id: 2, name: "Ar-Rahim", transliteration: "Ar-Rahīm", meaning: "The Most Merciful" },
  { id: 3, name: "Al-Malik", transliteration: "Al-Malik", meaning: "The King and Owner of Dominion" },
  { id: 4, name: "Al-Quddus", transliteration: "Al-Quddūs", meaning: "The Absolutely Pure" },
  { id: 5, name: "As-Salam", transliteration: "As-Salām", meaning: "The Perfection and Giver of Peace" },
  { id: 6, name: "Al-Mu'min", transliteration: "Al-Mu'min", meaning: "The One Who gives Emaan and Security" },
  { id: 7, name: "Al-Muhaymin", transliteration: "Al-Muhaymin", meaning: "The Guardian, The Witness, The Overseer" },
  { id: 8, name: "Al-Aziz", transliteration: "Al-Azīz", meaning: "The All Mighty" },
  { id: 9, name: "Al-Jabbar", transliteration: "Al-Jabbār", meaning: "The Compeller, The Restorer" },
  { id: 10, name: "Al-Mutakabbir", transliteration: "Al-Mutakabbir", meaning: "The Supreme, The Majestic" },
  { id: 11, name: "Al-Khaliq", transliteration: "Al-Khāliq", meaning: "The Creator, The Maker" },
  { id: 12, name: "Al-Bari", transliteration: "Al-Bāri'", meaning: "The Originator" },
  { id: 13, name: "Al-Musawwir", transliteration: "Al-Musawwir", meaning: "The Fashioner" },
  { id: 14, name: "Al-Ghaffar", transliteration: "Al-Ghaffār", meaning: "The All-Forgiving" },
  { id: 15, name: "Al-Qahhar", transliteration: "Al-Qahhār", meaning: "The Subduer, The Ever-Dominating" },
  { id: 16, name: "Al-Wahhab", transliteration: "Al-Wahhāb", meaning: "The Giver of Gifts" },
  { id: 17, name: "Ar-Razzaq", transliteration: "Ar-Razzāq", meaning: "The Provider" },
  { id: 18, name: "Al-Fattah", transliteration: "Al-Fattāh", meaning: "The Opener, The Judge" },
  { id: 19, name: "Al-Alim", transliteration: "Al-Alīm", meaning: "The All-Knowing, The Omniscient" },
  { id: 20, name: "Al-Qabid", transliteration: "Al-Qābid", meaning: "The Withholder" },
  { id: 21, name: "Al-Basit", transliteration: "Al-Bāsit", meaning: "The Extender" },
  { id: 22, name: "Al-Khafid", transliteration: "Al-Khāfid", meaning: "The Reducer, The Abaser" },
  { id: 23, name: "Ar-Rafi", transliteration: "Ar-Rāfi'", meaning: "The Exalter, The Elevator" },
  { id: 24, name: "Al-Mu'izz", transliteration: "Al-Mu'izz", meaning: "The Honourer, The Bestower" },
  { id: 25, name: "Al-Mudhill", transliteration: "Al-Mudhill", meaning: "The Dishonourer, The Humiliator" },
  { id: 26, name: "As-Sami", transliteration: "As-Samī'", meaning: "The All-Hearing" },
  { id: 27, name: "Al-Basir", transliteration: "Al-Basīr", meaning: "The All-Seeing" },
  { id: 28, name: "Al-Hakam", transliteration: "Al-Hakam", meaning: "The Judge, The Giver of Justice" },
  { id: 29, name: "Al-Adl", transliteration: "Al-Adl", meaning: "The Utterly Just" },
  { id: 30, name: "Al-Latif", transliteration: "Al-Latīf", meaning: "The Subtle One, The Most Gentle" },
  { id: 31, name: "Al-Khabir", transliteration: "Al-Khabīr", meaning: "The All-Aware" },
  { id: 32, name: "Al-Halim", transliteration: "Al-Halīm", meaning: "The Most Forbearing" },
  { id: 33, name: "Al-Azim", transliteration: "Al-Azīm", meaning: "The Magnificent, The Infinite" },
  { id: 34, name: "Al-Ghafur", transliteration: "Al-Ghafūr", meaning: "The All-Forgiving, The Ever-Forgiving" },
  { id: 35, name: "Ash-Shakur", transliteration: "Ash-Shakūr", meaning: "The Most Appreciative" },
  { id: 36, name: "Al-Ali", transliteration: "Al-Alī", meaning: "The Sublimely Exalted" },
  { id: 37, name: "Al-Kabir", transliteration: "Al-Kabīr", meaning: "The Greatest, The Most Grand" },
  { id: 38, name: "Al-Hafiz", transliteration: "Al-Hafīz", meaning: "The Preserver, The Guardian" },
  { id: 39, name: "Al-Muqit", transliteration: "Al-Muqīt", meaning: "The Sustainer" },
  { id: 40, name: "Al-Hasib", transliteration: "Al-Hasīb", meaning: "The Reckoner, The Sufficient" },
  { id: 41, name: "Al-Jalil", transliteration: "Al-Jalīl", meaning: "The Majestic" },
  { id: 42, name: "Al-Karim", transliteration: "Al-Karīm", meaning: "The Most Generous, The Most Esteemed" },
  { id: 43, name: "Ar-Raqib", transliteration: "Ar-Raqīb", meaning: "The Watchful" },
  { id: 44, name: "Al-Mujib", transliteration: "Al-Mujīb", meaning: "The Responsive One" },
  { id: 45, name: "Al-Wasi", transliteration: "Al-Wāsi'", meaning: "The All-Encompassing, the Boundless" },
  { id: 46, name: "Al-Hakim", transliteration: "Al-Hakīm", meaning: "The All-Wise" },
  { id: 47, name: "Al-Wadud", transliteration: "Al-Wadūd", meaning: "The Most Loving" },
  { id: 48, name: "Al-Majid", transliteration: "Al-Majīd", meaning: "The Glorious, The Most Honorable" },
  { id: 49, name: "Al-Ba'ith", transliteration: "Al-Bā'ith", meaning: "The Resurrector, The Raiser of the Dead" },
  { id: 50, name: "Ash-Shahid", transliteration: "Ash-Shahīd", meaning: "The All-and-Ever Witnessing" },
  { id: 51, name: "Al-Haqq", transliteration: "Al-Haqq", meaning: "The Absolute Truth" },
  { id: 52, name: "Al-Wakil", transliteration: "Al-Wakīl", meaning: "The Trustee, The Disposer of Affairs" },
  { id: 53, name: "Al-Qawiy", transliteration: "Al-Qawiyy", meaning: "The All-Strong" },
  { id: 54, name: "Al-Matin", transliteration: "Al-Matīn", meaning: "The Firm, The Steadfast" },
  { id: 55, name: "Al-Wali", transliteration: "Al-Waliyy", meaning: "The Protecting Associate" },
  { id: 56, name: "Al-Hamid", transliteration: "Al-Hamīd", meaning: "The Praiseworthy" },
  { id: 57, name: "Al-Muhsi", transliteration: "Al-Muhsī", meaning: "The All-Enumerating, The Counter" },
  { id: 58, name: "Al-Mubdi", transliteration: "Al-Mubdi'", meaning: "The Originator, The Initiator" },
  { id: 59, name: "Al-Mu'id", transliteration: "Al-Mu'īd", meaning: "The Restorer, The Reinstater" },
  { id: 60, name: "Al-Muhyi", transliteration: "Al-Muhyī", meaning: "The Giver of Life" },
  { id: 61, name: "Al-Mumit", transliteration: "Al-Mumīt", meaning: "The Bringer of Death, the Destroyer" },
  { id: 62, name: "Al-Hayy", transliteration: "Al-Hayy", meaning: "The Ever-Living" },
  { id: 63, name: "Al-Qayyum", transliteration: "Al-Qayyūm", meaning: "The Sustainer, The Self-Subsisting" },
  { id: 64, name: "Al-Wajid", transliteration: "Al-Wājid", meaning: "The Perceiver" },
  { id: 65, name: "Al-Majid", transliteration: "Al-Mājid", meaning: "The Illustrious, the Magnificent" },
  { id: 66, name: "Al-Wahid", transliteration: "Al-Wāhid", meaning: "The One" },
  { id: 67, name: "Al-Ahad", transliteration: "Al-Ahad", meaning: "The Unique, The Only One" },
  { id: 68, name: "As-Samad", transliteration: "As-Samad", meaning: "The Eternal, Satisfier of Needs" },
  { id: 69, name: "Al-Qadir", transliteration: "Al-Qādir", meaning: "The Capable, The Powerful" },
  { id: 70, name: "Al-Muqtadir", transliteration: "Al-Muqtadir", meaning: "The Omnipotent" },
  { id: 71, name: "Al-Muqaddim", transliteration: "Al-Muqaddim", meaning: "The Expediter, The One Who Brings Forward" },
  { id: 72, name: "Al-Mu'akhkhir", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer, the One Who Puts Far Behind" },
  { id: 73, name: "Al-Awwal", transliteration: "Al-Awwal", meaning: "The First" },
  { id: 74, name: "Al-Akhir", transliteration: "Al-Ākhir", meaning: "The Last" },
  { id: 75, name: "Az-Zahir", transliteration: "Az-Zāhir", meaning: "The Manifest" },
  { id: 76, name: "Al-Batin", transliteration: "Al-Bātin", meaning: "The Hidden One, Knower of the Hidden" },
  { id: 77, name: "Al-Wali", transliteration: "Al-Wālī", meaning: "The Governor, The Patron" },
  { id: 78, name: "Al-Muta'ali", transliteration: "Al-Muta'ālī", meaning: "The Self Exalted" },
  { id: 79, name: "Al-Barr", transliteration: "Al-Barr", meaning: "The Source of Goodness, the Kind Benefactor" },
  { id: 80, name: "At-Tawwab", transliteration: "At-Tawwāb", meaning: "The Ever-Pardoning, The Relenting" },
  { id: 81, name: "Al-Muntaqim", transliteration: "Al-Muntaqim", meaning: "The Avenger" },
  { id: 82, name: "Al-Afu", transliteration: "Al-Afuww", meaning: "The Pardoner" },
  { id: 83, name: "Ar-Ra'uf", transliteration: "Ar-Ra'ūf", meaning: "The Most Kind" },
  { id: 84, name: "Malik-ul-Mulk", transliteration: "Mālik-ul-Mulk", meaning: "Master of Kingdom, Owner of Dominion" },
  { id: 85, name: "Dhul-Jalali wal-Ikram", transliteration: "Dhū-l-Jalāli wa-l-Ikrām", meaning: "Possessor of Glory and Honour, Lord of Majesty and Generosity" },
  { id: 86, name: "Al-Muqsit", transliteration: "Al-Muqsit", meaning: "The Equitable, the Requiter" },
  { id: 87, name: "Al-Jami", transliteration: "Al-Jāmi'", meaning: "The Gatherer, the Uniter" },
  { id: 88, name: "Al-Ghani", transliteration: "Al-Ghaniyy", meaning: "The Self-Sufficient, The Wealthy" },
  { id: 89, name: "Al-Mughni", transliteration: "Al-Mughnī", meaning: "The Enricher" },
  { id: 90, name: "Al-Mani", transliteration: "Al-Māni'", meaning: "The Withholder" },
  { id: 91, name: "Ad-Darr", transliteration: "Ad-Dārr", meaning: "The Distresser" },
  { id: 92, name: "An-Nafi", transliteration: "An-Nāfi'", meaning: "The Propitious, the Benefactor" },
  { id: 93, name: "An-Nur", transliteration: "An-Nūr", meaning: "The Light, The Illuminator" },
  { id: 94, name: "Al-Hadi", transliteration: "Al-Hādī", meaning: "The Guide" },
  { id: 95, name: "Al-Badi", transliteration: "Al-Badī'", meaning: "The Incomparable Originator" },
  { id: 96, name: "Al-Baqi", transliteration: "Al-Bāqī", meaning: "The Ever-Surviving, The Everlasting" },
  { id: 97, name: "Al-Warith", transliteration: "Al-Wārith", meaning: "The Ultimate Inheritor" },
  { id: 98, name: "Ar-Rashid", transliteration: "Ar-Rashīd", meaning: "The Guide to the Right Path" },
  { id: 99, name: "As-Sabur", transliteration: "As-Sabūr", meaning: "The Forbearing, The Patient" }
];
