export const STORIES = [
  // Prophets
  {
    id: 'prophet-adam',
    title: 'The Story of Prophet Adam',
    subtitle: 'The first human, the first prophet, and the father of mankind.',
    category: 'Prophets',
    readTime: '10 min',
    content: 'Prophet Adam (peace be upon him) is the father of all humanity. Allah created him from clay and breathed life into him. Allah taught Adam the names of all things, demonstrating his superiority in knowledge over the angels.\n\nAllah commanded the angels to prostrate to Adam as a sign of respect. All obeyed except Iblis (Satan), who arrogantly refused, claiming he was better because he was made of fire while Adam was made of clay. As a result, Iblis was banished from Allah\'s mercy.\n\nAdam and his wife, Hawa (Eve), lived in Paradise. They were allowed to eat from any tree except one. Iblis deceived them, swearing he was their sincere advisor, and convinced them to eat from the forbidden tree. Immediately, they became aware of their nakedness and covered themselves with leaves.\n\nRealizing their mistake, Adam and Hawa repented sincerely, saying, "Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers." Allah, the Most Merciful, forgave them but decreed that they would live on Earth, where they and their descendants would face trials and eventually return to Him.\n\nAdam\'s story teaches us about the consequences of disobedience, the power of sincere repentance, and the unending mercy of Allah.'
  },
  {
    id: 'prophet-ibrahim',
    title: 'The Story of Prophet Ibrahim',
    subtitle: 'The Friend of Allah and the patriarch of monotheism.',
    category: 'Prophets',
    readTime: '15 min',
    content: 'Prophet Ibrahim (Abraham) is known as Khalilullah, the Friend of Allah. Born in a society of idol worshippers, including his own father, Ibrahim rejected the idols from a young age. He sought the truth by observing the stars, the moon, and the sun, concluding that the Creator of the universe must be One and eternal.\n\nHe challenged his people\'s beliefs by breaking their idols and leaving the biggest one intact, hanging an axe around its neck. When questioned, he told them to ask the big idol, proving that idols could neither speak nor defend themselves. Enraged, the people threw Ibrahim into a massive fire. However, Allah commanded the fire, "O fire, be coolness and safety upon Ibrahim," and he walked out unharmed.\n\nIbrahim faced many trials, including leaving his wife Hajar and infant son Ismail in the barren valley of Mecca. His ultimate test came when he was commanded in a dream to sacrifice his beloved son, Ismail. Both father and son submitted to Allah\'s will. As Ibrahim prepared to sacrifice Ismail, Allah replaced the boy with a ram, establishing the tradition of Udhiyah (Qurbani).\n\nTogether with Ismail, Ibrahim built the Kaaba in Mecca, establishing it as the center of monotheistic worship. Ibrahim\'s life is the ultimate example of unwavering faith, absolute submission, and complete trust in Allah.'
  },
  {
    id: 'prophet-musa',
    title: 'The Story of Prophet Musa',
    subtitle: 'A tale of patience, faith, and standing up to tyranny.',
    category: 'Prophets',
    readTime: '14 min',
    content: 'Prophet Musa (Moses) is one of the most frequently mentioned prophets in the Quran. He was born during a time when Pharaoh had ordered the killing of all newborn boys among the Israelites. His mother placed him in a basket and set it adrift on the Nile. Miraculously, he was found and adopted by Pharaoh\'s own family.\n\nAfter accidentally killing an Egyptian taskmaster, Musa fled to Midian, where he married and worked as a shepherd. Years later, on his way back to Egypt, he saw a burning bush on Mount Tur. There, Allah appointed him as a messenger and gave him miracles—his staff turning into a serpent and his hand shining white.\n\nMusa confronted Pharaoh, demanding the release of the Israelites. Despite witnessing the miracles and the subsequent plagues, Pharaoh remained arrogant. Eventually, Musa led his people out of Egypt. Trapped between Pharaoh\'s pursuing army and the Red Sea, Musa struck the water with his staff, parting it to allow the Israelites to cross safely. When Pharaoh and his army tried to follow, the sea crashed down, drowning them.\n\nThe story of Musa is a powerful reminder that Allah\'s will always prevails, and He is always with the oppressed who maintain their faith.'
  },
  {
    id: 'prophet-yusuf',
    title: 'The Story of Prophet Yusuf',
    subtitle: 'A beautiful narrative of betrayal, patience, and ultimate triumph.',
    category: 'Prophets',
    readTime: '15 min',
    content: 'Prophet Yusuf (Joseph) is the protagonist of Surah Yusuf, which the Quran calls "the best of stories." He was the beloved son of Prophet Yaqub (Jacob). Yusuf\'s ten older half-brothers grew intensely jealous of him and threw him into a dry well, telling their father a wolf had devoured him.\n\nYusuf was rescued by a passing caravan and sold into slavery in Egypt to a high-ranking minister. Growing up into a strikingly handsome and wise young man, Yusuf faced a new trial when the minister\'s wife tried to seduce him. Preferring prison over sin, Yusuf prayed to Allah for protection and was unjustly imprisoned.\n\nIn prison, Allah granted him the ability to interpret dreams. Years later, the King of Egypt had a disturbing dream about seven fat cows being eaten by seven lean ones. Yusuf explained that Egypt would face seven years of abundance followed by seven years of severe famine, advising them to store the surplus grain.\n\nImpressed by his wisdom, the King exonerated Yusuf and appointed him as the chief minister. When the famine struck, Yusuf\'s brothers came to Egypt seeking grain, not recognizing him. After a series of tests, Yusuf revealed his identity, forgiving them completely. The family was reunited in Egypt, fulfilling his childhood dream.'
  },
  {
    id: 'prophet-nuh',
    title: 'The Story of Prophet Nuh',
    subtitle: 'The steadfastness of a prophet over 950 years of preaching.',
    category: 'Prophets',
    readTime: '12 min',
    content: 'Prophet Nuh (Noah) is revered as one of the first major messengers sent by Allah to guide humanity back to monotheism. His people had fallen into idol worship, creating deities out of righteous men who had lived before them.\n\nFor 950 years, Nuh patiently called his people to worship Allah alone. He preached to them day and night, in public and in private. He warned them of the consequences of their disbelief and reminded them of Allah\'s blessings. However, his people mocked him, rejected his message, and only a small group of the poor and weak believed in him.\n\nEventually, Allah revealed to Nuh that no more of his people would believe. He was commanded to build a massive ark (ship) under Divine guidance. When the command of Allah came, water gushed forth from the earth, and rain poured from the skies. Nuh gathered the believers and a pair of every animal onto the ark.\n\nThe floodwaters rose, covering the highest mountains. Even Nuh\'s own son, who had disbelieved, drowned. The ark sailed safely over the devastating waves until the waters subsided, and it came to rest on Mount Judi. Nuh and the believers disembarked, establishing a new beginning for humanity.'
  },
  {
    id: 'prophet-yunus',
    title: 'The Story of Prophet Yunus',
    subtitle: 'The miraculous survival in the belly of the whale.',
    category: 'Prophets',
    readTime: '8 min',
    content: 'Prophet Yunus (Jonah) was sent to the city of Nineveh to call its people to worship Allah and abandon their sins. The people were stubborn and rejected his message. Frustrated and angry at their disbelief, Yunus left the city without waiting for Allah\'s permission, warning them of impending punishment.\n\nYusuf boarded a ship, but a massive storm struck. The sailors believed someone on board had brought bad luck and drew lots to throw someone overboard to save the ship. The lot fell on Yunus three times, and he realized it was a test from Allah. He was thrown into the raging sea.\n\nBy Allah\'s command, a giant whale swallowed Yunus whole. In the absolute darkness of the whale\'s belly, Yunus realized his mistake. He fervently repented, calling out, "La ilaha illa anta, subhanaka, inni kuntu minaz-zalimin" (There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers).\n\nAllah accepted his sincere repentance and commanded the whale to cast him onto the shore. Yunus was sick and weak, so Allah caused a gourd plant to grow over him to provide shade and nourishment. Once healed, Yunus returned to his people to find that they had repented and believed in Allah, saving themselves from the punishment. The story teaches us that we should never despair of Allah\'s mercy and that sincere repentance is always accepted.'
  },
  {
    id: 'prophet-sulaiman',
    title: 'The Story of Prophet Sulaiman',
    subtitle: 'The wise king who commanded the wind, jinn, and animals.',
    category: 'Prophets',
    readTime: '11 min',
    content: 'Prophet Sulaiman (Solomon) was the son of Prophet Dawud (David). Allah blessed him with unparalleled wisdom, a magnificent kingdom, and control over elements that no other human has ever had. He could understand the language of birds and animals, command the wind to travel vast distances in a short time, and control the Jinn, who built massive structures and dived into the sea for him.\n\nDespite his immense power and wealth, Sulaiman remained a humble and grateful servant of Allah. Once, while marching with his massive army of men, jinn, and birds, they approached a valley of ants. Sulaiman heard a female ant warning the others to enter their dwellings lest Sulaiman and his army crush them unawares. Sulaiman smiled at her words and immediately prayed to Allah in gratitude for His blessings.\n\nHis kingdom also encountered the Queen of Sheba (Bilqis), whose people worshipped the sun. Sulaiman sent her a letter inviting her to submit to Allah. After witnessing the miracles and the grandeur of Sulaiman\'s kingdom—including a palace with a floor made of transparent glass over water—Bilqis recognized the truth and embraced Islam.\n\nSulaiman\'s death was also a profound lesson. He passed away while leaning on his staff, but he remained standing for a long time. The Jinn, thinking he was alive, continued their hard labor. It was only when a termite ate away his staff and he fell that the Jinn realized he had died, proving to them and humanity that only Allah possesses the knowledge of the unseen.'
  },
  {
    id: 'sulaiman-and-ants',
    title: 'Sulaiman and the Ants',
    subtitle: 'A profound lesson in humility, leadership, and gratitude.',
    category: 'Quranic Tales',
    content: 'The story of Prophet Sulaiman (Solomon) and the valley of the ants is a beautiful narrative mentioned in Surah An-Naml (The Ants). Allah had granted Sulaiman a kingdom unlike any other, giving him control over the wind, the jinn, and the ability to understand the language of birds and animals.\n\nOne day, Sulaiman was marching with his massive, magnificent army composed of men, jinn, and birds. They were marching in strict discipline and order. As they approached the Valley of the Ants, a tiny, seemingly insignificant creature—a female ant—noticed the approaching army.\n\nRealizing the danger her colony was in, the ant called out to her companions, "O ants, enter your dwellings that you not be crushed by Sulaiman and his soldiers while they perceive not." This remarkable statement demonstrated the ant\'s recognition of Sulaiman and his army, her sense of responsibility towards her community, and her understanding that Sulaiman and his righteous army would never intentionally harm them.\n\nSulaiman, who could hear and understand her from a distance, smiled in amusement at her words. Despite his immense power, he did not ignore this tiny creature. Instead, her words profoundly moved him. He halted his massive army to allow the ants to safely enter their homes.\n\nMore importantly, Sulaiman immediately turned to Allah in prayer, saying: "My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents and to do righteousness of which You approve. And admit me by Your mercy into [the ranks of] Your righteous servants."\n\nThis story is a profound lesson in leadership and humility. It shows that true power is not about being oppressive, but about being mindful of the weakest members of society. It also teaches that every blessing should be met with immense gratitude to Allah.'
  },
  {
    id: 'prophet-isa',
    title: 'The Story of Prophet Isa',
    subtitle: 'The miraculous birth and the message of love and submission.',
    category: 'Prophets',
    readTime: '12 min',
    content: 'Prophet Isa (Jesus) holds a unique position in Islam as a mighty messenger of Allah. His birth was a miracle; he was born to the pure and chaste Virgin Maryam (Mary) without a human father, by the decree of Allah: "Be, and it is."\n\nWhen Maryam returned to her people carrying the infant Isa, they accused her of wrongdoing. In defense of his mother\'s honor, the infant Isa spoke from the cradle, announcing, "Indeed, I am the servant of Allah. He has given me the Scripture and made me a prophet."\n\nIsa grew up to deliver the message of the Injeel (Gospel) to the Children of Israel. He was granted extraordinary miracles by Allah\'s permission: he healed the blind and the lepers, brought the dead back to life, and fashioned the shape of a bird from clay and breathed into it, making it a living bird. These miracles were signs of Allah\'s power and a validation of Isa\'s prophethood.\n\nDespite his clear signs, the religious elite of his time rejected him and plotted to crucify him. However, the Quran teaches that they did not kill him, nor did they crucify him. Instead, Allah raised Isa up to Himself, protecting His messenger. Islam teaches that Isa will return before the Day of Judgment to restore justice and defeat the Antichrist (Dajjal).'
  },
  {
    id: 'prophet-muhammad',
    title: 'The Story of Prophet Muhammad (PBUH)',
    subtitle: 'The Seal of the Prophets and the mercy to the worlds.',
    category: 'Prophets',
    readTime: '20 min',
    content: 'Prophet Muhammad (peace be upon him) is the final messenger sent by Allah to humanity. Born in Mecca in 570 CE, he was orphaned at a young age. Known for his impeccable honesty and character, he was called "Al-Amin" (The Trustworthy).\n\nAt the age of 40, while meditating in the Cave of Hira, the Angel Jibril (Gabriel) appeared to him and revealed the first verses of the Quran: "Read in the name of your Lord who created..." Over the next 23 years, the Quran was revealed to him, serving as the ultimate guidance for mankind.\n\nFor 13 years in Mecca, the Prophet faced immense persecution, boycotts, and assassination attempts from the Quraysh leaders for preaching the Oneness of Allah. To protect the growing Muslim community, he migrated to Medina (the Hijrah), marking the beginning of the Islamic calendar.\n\nIn Medina, the Prophet established a thriving, just society based on brotherhood and faith. He faced several defensive battles, including Badr, Uhud, and the Trench, ultimately securing the survival of Islam. In the year 8 AH, he returned to Mecca as a conqueror, but rather than seeking revenge against those who had tortured him and his followers, he granted a general amnesty, showing unparalleled mercy.\n\nBefore his passing, the entire Arabian Peninsula had embraced Islam. Prophet Muhammad\'s life is the perfect example (Sunnah) of compassion, justice, devotion, and leadership. He is the Seal of the Prophets, carrying a message meant for all people and all times.'
  },

  // Past Events
  {
    id: 'event-elephant',
    title: 'The Year of the Elephant',
    subtitle: 'The miraculous protection of the Kaaba from Abraha\'s army.',
    category: 'Past Events',
    readTime: '7 min',
    content: 'The Year of the Elephant (Am al-Fil) marks a momentous event that occurred in 570 CE, the same year Prophet Muhammad (PBUH) was born. Abraha, a powerful ruler in Yemen, had built a magnificent cathedral in Sana\'a and wanted to divert the Arab pilgrimage from the Kaaba in Mecca to his new cathedral.\n\nWhen the Arabs ignored his cathedral, Abraha became furious and decided to march on Mecca with a massive army to destroy the Kaaba. His army included a formidable force of war elephants, led by a massive elephant named Mahmud.\n\nAs the army approached Mecca, the Quraysh, realizing they could not defeat such a force, fled to the surrounding mountains, leaving the Kaaba in the hands of Allah. When Abraha commanded his lead elephant, Mahmud, to advance towards the Kaaba, the elephant refused to move. It would walk in any other direction but would kneel when turned towards Mecca.\n\nSuddenly, Allah sent flocks of small birds (Ababil) from the sea. Each bird carried three small stones of baked clay—one in its beak and one in each claw. The birds pelted Abraha\'s army with these stones. The stones pierced through the soldiers\' armor and bodies like bullets, devastating the army and leaving them like "chewed up straw," as described in Surah Al-Fil.\n\nAbraha\'s army was utterly destroyed, and the Kaaba was protected by the Divine intervention of Allah, serving as a sign of its sanctity.'
  },
  {
    id: 'event-badr',
    title: 'The Battle of Badr',
    subtitle: 'The decisive victory of faith over overwhelming numbers.',
    category: 'Past Events',
    readTime: '9 min',
    content: 'The Battle of Badr, which took place in the second year after the Hijrah (migration) to Medina, was the first major military confrontation between the early Muslims and the powerful Quraysh tribe of Mecca.\n\nThe Muslims, numbering only 313 men with very few horses and rudimentary weapons, marched to intercept a Meccan caravan. However, the caravan escaped, and instead, the Muslims found themselves facing a heavily armed Meccan army of over 1,000 men, led by Abu Jahl, the fiercest enemy of Islam.\n\nBefore the battle, the Prophet Muhammad (PBUH) prayed fervently to Allah, knowing that if this small band of believers were destroyed, Islam might perish from the earth. Allah promised His support, sending down thousands of angels to fight alongside the Muslims.\n\nDespite being drastically outnumbered, the Muslims fought with unparalleled courage and conviction. The Meccan leadership was decimated, with key figures like Abu Jahl being killed. The Muslims emerged victorious, taking many prisoners of war.\n\nThe victory at Badr was a turning point in Islamic history. It solidified the Prophet\'s authority in Medina and proved that spiritual conviction and Divine support could overcome any physical disadvantage. The Quran refers to the day of Badr as "Yawm al-Furqan" – the day the criterion between truth and falsehood was established.'
  },
  {
    id: 'event-boy-and-king',
    title: 'The Boy and the King (Ashab Al-Ukhdud)',
    subtitle: 'A young boy\'s unshakeable faith that transformed a nation.',
    category: 'Past Events',
    readTime: '10 min',
    content: 'This powerful story, referenced in Surah Al-Buruj, tells of a tyrannical king who claimed to be a god and employed an aging sorcerer. The sorcerer requested a young boy to pass on his dark knowledge. However, on his way to the sorcerer, the boy met a devout monk who taught him about the true, One God (Allah).\n\nThe boy embraced the monk\'s teachings. Allah granted him the ability to heal the blind and cure diseases, but the boy always clarified that the healing came from Allah alone. A blind courtier of the king was healed by the boy\'s prayers and subsequently declared his belief in Allah. Enraged, the king tortured the courtier and the monk until they died, refusing to renounce their faith.\n\nThe king then tried to kill the boy. He sent him up a mountain to be thrown off, but the boy prayed, and the mountain shook, killing the guards. He sent him in a boat to be drowned, but the boy prayed, and the boat capsized the guards. Returning to the king, the boy said, "You cannot kill me unless you do as I command."\n\nThe boy instructed the king to gather the entire city, tie him to a tree, take an arrow from the boy\'s quiver, and shoot him while saying, "In the name of Allah, the Lord of the boy." The arrogant king did exactly that, and the boy died. Witnessing this profound sacrifice, the entire crowd cried out, "We believe in the Lord of the boy!"\n\nThe king, in his fury, ordered massive trenches (Ukhdud) to be dug and filled with fire, throwing any believer into the flames. Despite the horrific execution, the people remained steadfast in their faith, choosing the eternal fire of the trench over denying Allah.'
  },
  {
    id: 'event-conquest-mecca',
    title: 'The Conquest of Mecca',
    subtitle: 'The peaceful return and the ultimate display of mercy.',
    category: 'Past Events',
    readTime: '8 min',
    content: 'The Conquest of Mecca (Fath Makkah) took place in the 8th year of Hijrah and is one of the most remarkable bloodless victories in human history. After the Quraysh broke the Treaty of Hudaybiyyah by attacking an allied tribe of the Muslims, the Prophet Muhammad (PBUH) mobilized an army of 10,000 men and marched towards Mecca.\n\nThe Meccans, who had persecuted, tortured, and waged war against the Muslims for over two decades, were terrified. As the massive Muslim army entered the city from four directions, there was virtually no resistance. The Prophet entered his hometown with his head bowed so low in humility to Allah that his beard almost touched his camel\'s saddle.\n\nHe proceeded to the Kaaba and smashed the 360 idols that surrounded it, reciting: "Truth has come, and falsehood has departed. Indeed is falsehood, [by nature], ever bound to depart."\n\nThe Quraysh gathered around the Kaaba, awaiting their fate. The Prophet asked them, "O Quraysh, what do you think I am going to do with you?" They replied, "You are a noble brother, son of a noble brother." The Prophet then delivered his historic decree of mercy: "Go, for you are free. Today there is no blame upon you."\n\nThis unmatched act of forgiveness touched the hearts of the Meccans, leading them to embrace Islam in droves. The Conquest of Mecca stands as a testament to the fact that Islam triumphed not through the sword, but through faith, patience, and supreme mercy.'
  },
  {
    id: 'event-hajar-zamzam',
    title: 'Hajar and the Well of Zamzam',
    subtitle: 'A mother\'s struggle and Allah\'s miraculous provision.',
    category: 'Past Events',
    readTime: '6 min',
    content: 'The story of Hajar (Hagar) and the well of Zamzam is deeply woven into the rituals of Hajj and Umrah. Prophet Ibrahim was commanded by Allah to leave his wife Hajar and their infant son Ismail in the barren, uncultivated valley of Mecca. Hajar asked Ibrahim if Allah had commanded him to do this. When he replied yes, her faith shone through: "Then He will not neglect us."\n\nWhen their provisions of water ran out, the infant Ismail began to cry from intense thirst. The desperate mother ran back and forth between two small hills, Safa and Marwah, frantically searching for water or a passing caravan. She ran between the hills seven times, a struggle that is commemorated by millions of pilgrims today in the ritual of Sa\'i.\n\nAfter her seventh run, she heard a voice and saw the Angel Jibril (Gabriel) where Ismail lay. Jibril struck the ground with his wing (or heel), and miraculously, fresh water began to gush forth. Hajar quickly gathered sand around the water to contain it, saying "Zom, Zom" (stop, stop), giving the well its name, Zamzam.\n\nThis miraculous well provided for Hajar and Ismail and eventually attracted the tribe of Jurhum to settle in the area, leading to the foundation of the city of Mecca. Hajar\'s story is a beautiful illustration of tawakkul (trust in Allah) and the immense love and struggle of a mother.'
  },
  // Keep Sahabah and others
  {
    id: 'sahabah-salman',
    title: 'Salman al-Farsi',
    subtitle: 'The search for truth across different lands and religions.',
    category: 'Sahabah',
    readTime: '8 min',
    content: 'Salman al-Farsi was a companion of the Prophet Muhammad (PBUH) known for his incredible journey in search of the true religion. Born in Persia to a wealthy Zoroastrian family, Salman was deeply devoted to the sacred fire.\n\nHis spiritual thirst led him to travel to Syria to learn from Christian monks. As each monk approached death, Salman would ask for guidance, and he was continually directed to the next righteous scholar. Eventually, the last monk told him that the time for a new prophet was near, one who would appear in Arabia.\n\nSalman journeyed towards Arabia but was betrayed and sold into slavery in Medina. When the Prophet Muhammad (PBUH) migrated to Medina, Salman recognized the signs of prophethood on him.\n\nSalman embraced Islam and played a crucial role in the Muslim community. He is famously known for suggesting the strategy of digging a trench (Khandaq) around Medina to defend against the coalition of enemy forces. Salman\'s life is a testament to the sincere and relentless pursuit of truth.'
  },
  {
    id: 'sahabah-bilal',
    title: 'Bilal ibn Rabah',
    subtitle: 'From a persecuted slave to the first Muezzin of Islam.',
    category: 'Sahabah',
    readTime: '6 min',
    content: 'Bilal ibn Rabah was an Abyssinian slave living in Mecca when the message of Islam was first preached. Despite the immense danger, Bilal embraced Islam, deeply resonating with its message of equality and the Oneness of Allah.\n\nWhen his master discovered Bilal\'s conversion, he subjected him to brutal torture. In the scorching heat of the Arabian desert, he would pin Bilal to the ground and place a massive, burning boulder on his chest. But Bilal\'s faith was unshakable. He continuously repeated "Ahad, Ahad" (One, One), affirming his belief in the one true God.\n\nHis remarkable endurance caught the attention of Abu Bakr, who bought Bilal and set him free.\n\nWhen the Muslims migrated to Medina and the call to prayer (Adhan) was instituted, the Prophet chose Bilal to be the first Muezzin of Islam. His deep, melodious voice echoed across Medina. Following the conquest of Mecca, it was Bilal who climbed atop the Kaaba to declare the Adhan, symbolizing the ultimate victory of truth over ignorance.'
  },
  {
    id: 'companions-cave',
    title: 'Companions of the Cave',
    subtitle: 'The youth who sought refuge in the cave to protect their faith.',
    category: 'Quranic Tales',
    readTime: '7 min',
    content: 'The story of the Companions of the Cave (Ashab al-Kahf) is narrated in Surah Al-Kahf. It is a beautiful story about a group of righteous youth who lived in a city ruled by a tyrannical king who forced his people to worship idols.\n\nRejecting the polytheism of their society, these young men secretly believed in the Oneness of Allah. When their faith was discovered, they faced persecution. To protect their religion, they fled the city and took refuge in a secluded cave, accompanied by their loyal dog.\n\nIn the cave, they prayed to Allah for mercy. Allah answered their prayers by placing them into a deep sleep that lasted for over 300 years. During this time, the world outside changed drastically; the city had embraced monotheism.\n\nWhen they awoke, they thought they had only slept for a day. They sent one of their companions to the city with an old coin to buy food. The shopkeeper, seeing the ancient coin, was astonished, and the secret of the sleepers was revealed to the city.\n\nThe people rejoiced at witnessing this miracle of resurrection. Their story stands as an eternal testament to Allah\'s power to protect those who rely on Him and the reality of life after death.'
  },
  {
    id: 'prophet-ayyub',
    title: 'The Story of Prophet Ayyub',
    subtitle: 'An enduring symbol of patience and trust in Allah during extreme affliction.',
    category: 'Prophets',
    readTime: '8 min',
    content: 'Prophet Ayyub (Job) was a wealthy, healthy, and highly respected prophet of Allah, blessed with a large family and vast properties. However, Allah decided to test his faith to serve as an example for all of humanity.\n\nIn a series of rapid misfortunes, Ayyub lost all his wealth, his property was destroyed, and tragically, his children perished. Furthermore, he was struck by a severe and repulsive illness that left him bedridden for years. His friends and community abandoned him, with only his loyal wife staying by his side to care for him.\n\nDespite losing everything, Ayyub never complained. He remained in a state of continuous remembrance and gratitude to Allah. After many long years of intense suffering, Ayyub finally made a beautiful, humble prayer to his Lord: "Indeed, adversity has touched me, and You are the most merciful of the merciful."\n\nAllah answered his prayer, instructing him to strike the ground with his foot. A cool spring gushed forth; he washed in it and drank from it, and was miraculously cured of all his illnesses. Allah not only restored his health but returned his wealth manifold and blessed him with an even larger family. Ayyub’s story teaches us that true patience (Sabr Jameel) and unwavering faith in Allah’s mercy will ultimately lead to incredible rewards.'
  },
  {
    id: 'maryam-mother-of-isa',
    title: 'Maryam, the Mother of Isa',
    subtitle: 'A life of absolute purity, devotion, and miraculous grace.',
    category: 'Quranic Tales',
    readTime: '10 min',
    content: 'Maryam (Mary) holds a deeply exalted status in Islam, being the only woman mentioned by name in the Quran. Her mother had dedicated her to the service of Allah even before her birth. Maryam grew up in the sanctuary (Mihrab) under the care of Prophet Zakariya.\n\nShe spent her days in deep prayer and devotion. Zakariya would often find miraculous provisions of out-of-season fruits in her sanctuary. When he asked where she got them, Maryam simply replied, "It is from Allah. Indeed, Allah provides for whom He wills without account."\n\nOne day, the Angel Jibril (Gabriel) appeared to her in the form of a man to give her the glad tidings of a son, Isa (Jesus). Maryam was shocked, as no man had ever touched her, and she was chaste. Jibril told her that it is easy for Allah; He only says "Be," and it is.\n\nMaryam withdrew to a distant place to give birth, enduring the pains of childbirth alone under a date palm tree. In her distress, Allah provided a stream of water beneath her and fresh dates from the tree above. When she returned to her people carrying the infant Isa, they accused her. By the miracle of Allah, the baby Isa spoke from his cradle to defend her purity and announce his prophethood. Maryam\'s absolute trust in Allah made her a timeless symbol of piety and faith.'
  },
  {
    id: 'the-two-gardens',
    title: 'The Story of the Two Gardens',
    subtitle: 'A profound parable about wealth, arrogance, and gratitude.',
    category: 'Quranic Tales',
    readTime: '7 min',
    content: 'This powerful parable is found in Surah Al-Kahf. It tells the story of two men. One was exceptionally wealthy, blessed by Allah with two magnificent gardens of grapevines, surrounded by date palms, with a river flowing between them. The gardens yielded abundant fruit without fail.\n\nThe wealthy man, however, grew arrogant. As he walked through his spectacular gardens with his less fortunate companion, he boasted: "I am greater than you in wealth and mightier in men." He foolishly believed his wealth was the result of his own greatness and claimed that his gardens would never perish, even doubting the coming of the Day of Judgment.\n\nHis humble companion admonished him, reminding him that everything he had was a gift from Allah, the One who created him from dust. He advised the wealthy man to say, "Masha\'Allah, la quwwata illa billah" (What Allah willed has occurred; there is no power except in Allah) when entering his garden.\n\nThe arrogant man ignored the warning. Consequently, Allah sent a calamity upon his gardens overnight. The vineyards were destroyed, and the land became barren. The wealthy man was left wringing his hands in regret over what he had spent on it, realizing too late that his wealth could not save him, and that true power and provision lie solely with Allah.'
  },
  {
    id: 'prophet-salih',
    title: 'Prophet Salih and the She-Camel',
    subtitle: 'The miracle of the she-camel and the arrogance of Thamud.',
    category: 'Prophets',
    readTime: '9 min',
    content: 'Prophet Salih was sent to the people of Thamud, who lived in houses carved beautifully out of mountains. They were wealthy and skilled builders but had fallen into idol worship and arrogance. Salih, known for his wisdom and virtue, called them to worship Allah alone.\n\nDemanding proof of his prophethood, the people challenged Salih to bring forth a specific miracle: a huge, pregnant she-camel emerging from a solid rock. Salih prayed to Allah, and miraculously, the exact she-camel they described emerged from the mountain. Salih warned them: "This is the she-camel of Allah [as] a sign for you. So leave her to eat within Allah\'s land and do not touch her with harm, lest there seize you a painful punishment."\n\nFor a time, they coexisted; the she-camel would drink from the well one day, providing immense amounts of milk, and the people would drink the next. However, the arrogant leaders of Thamud grew resentful of the she-camel, seeing her as a symbol of Salih\'s authority. Defying Salih\'s warning, they cruelly slaughtered the innocent animal.\n\nSalih told them they had three days left to enjoy their lives in their homes before the punishment would arrive. On the third day, a massive, terrifying thunderbolt and earthquake struck Thamud, destroying them completely in their homes, leaving them as if they had never existed there.'
  },
  {
    id: 'prophet-lut',
    title: 'Prophet Lut and the City of Sodom',
    subtitle: 'A stark warning against unnatural sins and moral corruption.',
    category: 'Prophets',
    readTime: '8 min',
    content: 'Prophet Lut (Lot), the nephew of Prophet Ibrahim, was sent to the city of Sodom. The people of Sodom were notorious for their unprecedented immorality; they practiced highway robbery, engaged in public obscenities, and were the first in history to practice homosexuality, openly rejecting the natural order created by Allah.\n\nLut persistently warned them to fear Allah and abandon their shameful acts, but they mocked him and threatened to expel him for being "too pure." Even Lut\'s own wife did not truly believe in his message and sided with the corrupt townsfolk.\n\nAllah sent angels in the form of incredibly handsome young men to visit Lut. When the men of the city heard of these guests, they surrounded Lut\'s house, demanding that he hand them over. Distressed, Lut tried to protect his guests. The angels then revealed their true identity to Lut, assuring him that the people could not harm them.\n\nThe angels instructed Lut to leave the city with his family during the night and told them not to look back, except for his wife, who would share the fate of the city. As morning approached, a terrifying rain of brimstone and baked clay rained down upon Sodom, and the city was turned upside down, utterly destroying the wicked people.'
  },
  {
    id: 'prophet-shuayb',
    title: 'Prophet Shu\'ayb and the People of Madyan',
    subtitle: 'The prophet who fought against economic corruption and dishonesty.',
    category: 'Prophets',
    readTime: '8 min',
    content: 'Prophet Shu\'ayb was sent to the people of Madyan (Midian), a wealthy community that sat on a major trade route. While they prospered in trade, they were notorious for their economic corruption. They worshipped a tangled tree (Al-Aykah) and systematically cheated people by giving short measure and weight in their business dealings.\n\nShu\'ayb, known for his eloquent speech, passionately called them to worship Allah alone and to be fair in their trade. He warned them: "O my people, give full measure and weight in justice and do not deprive the people of their due and do not commit abuse on the earth, spreading corruption."\n\nDespite his sincere advice, the arrogant leaders mocked him, asking if his prayers commanded them to leave the gods of their forefathers or to stop doing as they wished with their wealth. They threatened to stone him or drive him out of the city.\n\nWhen they continuously rejected the truth and challenged Shu\'ayb to bring down a punishment from the sky, Allah\'s decree came to pass. An unbearable, suffocating heat struck Madyan. When a dark cloud appeared, they gathered under it hoping for rain, but instead, a devastating earthquake and a terrible cry from the sky overtook them, leaving them lifeless in their homes.'
  },
  {
    id: 'musa-and-khidr',
    title: 'Musa and Al-Khidr',
    subtitle: 'A journey uncovering the hidden wisdom behind Allah\'s decrees.',
    category: 'Quranic Tales',
    readTime: '12 min',
    content: 'The profound story of Prophet Musa (Moses) and Al-Khidr is detailed in Surah Al-Kahf. Once, Musa delivered a powerful sermon, and someone asked him if there was anyone more knowledgeable than him. Musa replied "No." Allah corrected Musa, revealing that a servant named Al-Khidr, located where the two seas meet, possessed knowledge of the unseen granted by Allah.\n\nMusa set out to find Al-Khidr, determined to learn from him. When they met, Al-Khidr warned Musa that he would not have the patience to accompany him, as he would witness things he couldn\'t understand. Musa promised to be patient and not question him.\n\nThey embarked on a boat, and to Musa\'s shock, Al-Khidr intentionally damaged it. Later, they met a young boy, and Al-Khidr killed him. Finally, they arrived at a town that refused them hospitality. Despite their hunger and the town\'s rudeness, Al-Khidr repaired a falling wall there without asking for payment. Musa, unable to bear it, questioned every action.\n\nAl-Khidr then explained the hidden wisdom: The boat belonged to poor fishermen, and a tyrant king was seizing all sound boats; damaging it saved their livelihood. The boy was destined to grow up into a wicked disbeliever who would severely oppress his righteous parents; Allah would replace him with a better child. The wall belonged to two orphan boys, and beneath it was a hidden treasure left by their righteous father; repairing it protected their inheritance until they came of age. This story teaches that human comprehension is limited, and Allah\'s wisdom is infinite.'
  },
  {
    id: 'qarun-and-his-wealth',
    title: 'Qarun (Korah) and His Wealth',
    subtitle: 'The tragic end of a man consumed by immense wealth and arrogance.',
    category: 'Quranic Tales',
    readTime: '8 min',
    content: 'Qarun was from the people of Prophet Musa, but he became exceedingly wealthy and arrogant. His wealth was so immense that just the keys to his treasuries were a heavy burden for a group of strong men to carry.\n\nInstead of being grateful to Allah and using his wealth for good, Qarun flaunted his riches. When his righteous people advised him not to exult in his wealth and to seek the Hereafter while not forgetting his share of the world, Qarun arrogantly replied, "I was only given it because of knowledge I have." He denied that his wealth was a blessing from Allah, attributing it solely to his own brilliance.\n\nOne day, Qarun went out among his people in his full adornment, parading his wealth. Those whose desires were focused on worldly life looked at him with intense envy, wishing they had what he was given. But those endowed with spiritual knowledge said, "Woe to you! The reward of Allah is better for he who believes and does righteousness."\n\nTo make an example of Qarun\'s arrogance, Allah caused the earth to swallow him and his spectacular mansion. He had no group to protect him from Allah, nor could he defend himself. Those who had envied him the day before realized the truth, saying, "Oh, how Allah extends provision to whom He wills of His servants and restricts it! If not that Allah had conferred favor on us, He would have caused it to swallow us." This story remains a stark warning against the destructive nature of arrogance and materialism.'
  },
  {
    id: 'dhul-qarnayn',
    title: 'Dhul-Qarnayn and the Great Wall',
    subtitle: 'The righteous king who traveled the earth establishing justice.',
    category: 'Quranic Tales',
    readTime: '10 min',
    content: 'The story of Dhul-Qarnayn (The Two-Horned One) is found in Surah Al-Kahf. He was a powerful and righteous king to whom Allah granted vast authority and the means to achieve great things. He undertook three major expeditions across the earth to establish justice and faith.\n\nFirst, he traveled to the furthest west, where he found the sun setting in a muddy spring. He found a people there and was given the choice to punish or be kind to them. He ruled with justice, punishing the wrongdoers and rewarding the righteous.\n\nNext, he traveled to the furthest east, where he found a people who had no shelter from the sun. He continued his journey until he reached a valley between two massive mountains.\n\nThere, he encountered a people whose language he could barely understand. They pleaded with Dhul-Qarnayn for help against Yajuj and Majuj (Gog and Magog), corrupt and destructive tribes that constantly ravaged their lands. They offered to pay him tribute to build a barrier.\n\nRefusing the tribute, Dhul-Qarnayn asked for their labor instead. He instructed them to bring blocks of iron, stacking them until the gap between the mountains was filled. He then ordered them to blow on fires until the iron became red hot, and poured molten copper over it. This created an impenetrable, smooth wall that Yajuj and Majuj could neither scale nor pierce. Dhul-Qarnayn attributed this magnificent feat entirely to the mercy of Allah, stating that when Allah\'s promise comes, the wall will be leveled to dust.'
  },
  {
    id: 'talut-and-jalut',
    title: 'Talut and Jalut (David and Goliath)',
    subtitle: 'A story of leadership, divine selection, and the power of faith.',
    category: 'Past Events',
    readTime: '9 min',
    content: 'After the time of Prophet Musa, the Children of Israel were oppressed and driven from their homes. They asked their prophet to appoint a king so they could fight in the way of Allah. The prophet announced that Allah had chosen Talut (Saul) as their king.\n\nThe nobles objected, claiming Talut lacked wealth and noble lineage. The prophet explained that Allah had chosen him for his abundance in knowledge and physical stature, and the sign of his kingship would be the return of the Ark of the Covenant, carried by angels.\n\nWhen Talut marched out with his army, he tested their obedience at a river. He commanded them not to drink from it, except for a handful of water. Most of the soldiers failed the test and drank deeply, losing their courage. Only a small, devout minority obeyed and crossed the river with him.\n\nFacing the massive, heavily armed enemy led by the terrifying giant Jalut (Goliath), many believers felt intimidated. But the steadfast ones said, "How many a small company has overcome a large company by permission of Allah."\n\nAmong Talut\'s army was a young Prophet Dawud (David). Armed with only a sling and deep faith, Dawud faced the towering Jalut. He struck Jalut with a stone, killing him instantly, and the massive enemy army was routed. Dawud was subsequently granted kingship and prophethood by Allah.'
  },
  {
    id: 'luqman-the-wise',
    title: 'Luqman the Wise',
    subtitle: 'The timeless advice of a father to his son.',
    category: 'Quranic Tales',
    readTime: '7 min',
    content: 'Luqman was not a prophet, but a highly righteous and wise man. Surah Luqman is named after him, and it beautifully details the profound advice he gave to his son.\n\nLuqman\'s first and most critical piece of advice was about Tawheed (Oneness of God): "O my son, do not associate [anything] with Allah. Indeed, association [with him] is great injustice." He then reminded his son of Allah\'s infinite knowledge, stating that even if a deed is the weight of a mustard seed, hidden in a rock, or in the heavens or the earth, Allah will bring it forth.\n\nHe advised his son to establish prayer, enjoin what is right, forbid what is wrong, and to bear with patience whatever befalls him, as these are matters of great resolve.\n\nFurthermore, Luqman provided timeless guidance on character and manners. He told his son not to turn his cheek in contempt toward people and not to walk on the earth exultantly, for Allah does not like the arrogant boaster. He concluded his advice by telling him to be moderate in his pace and to lower his voice, as the harshest of sounds is the braying of a donkey.\n\nLuqman\'s wisdom serves as a comprehensive manual for raising a righteous, humble, and morally upright child.'
  },
  {
    id: 'habil-and-qabil',
    title: 'Habil and Qabil (Cain and Abel)',
    subtitle: 'The story of the first murder and the destructive nature of envy.',
    category: 'Quranic Tales',
    readTime: '7 min',
    content: 'Habil (Abel) and Qabil (Cain) were the sons of Prophet Adam. The story of their conflict, the first crime committed on earth, is a profound lesson on envy, intention, and violence.\n\nBoth brothers were asked to offer a sacrifice to Allah. Habil, a shepherd, offered the very best of his flock with sincere devotion and a pure heart. Qabil, a farmer, offered some of his worst crops, lacking sincerity. Allah accepted Habil\'s sacrifice and rejected Qabil\'s.\n\nConsumed by jealousy and pride, Qabil threatened to kill his brother. Habil, possessing true piety, responded calmly, saying that Allah only accepts from the righteous. He added, "If you should raise your hand against me to kill me - I shall not raise my hand against you to kill you. Indeed, I fear Allah, Lord of the worlds."\n\nDespite Habil\'s peaceful response, Qabil\'s soul prompted him to commit the heinous act, and he murdered his brother. Afterward, Qabil did not know what to do with the body. Allah sent a raven that scratched the ground to bury another dead raven, teaching Qabil how to bury his brother. Qabil was struck with immense remorse and regret, becoming one of the losers.\n\nThis tragic event established the Quranic principle: "Whoever kills a soul unless for a soul or for corruption [done] in the land - it is as if he had slain mankind entirely. And whoever saves one - it is as if he had saved mankind entirely."'
  },
  {
    id: 'sahabah-abu-bakr',
    title: 'Abu Bakr As-Siddiq: The Truthful',
    subtitle: 'The first Caliph, closest companion, and the paragon of sincere faith.',
    category: 'Sahabah',
    readTime: '11 min',
    content: 'Abu Bakr As-Siddiq (may Allah be pleased with him) was the closest friend, confidant, and greatest companion of Prophet Muhammad (peace be upon him). He was the first free adult male to accept Islam without a moment of hesitation. When the Quraysh mocked the miraculous Night Journey and Ascension (Al-Isra wal-Mi\'raj), Abu Bakr declared with unshakable conviction: "If he said so, then it is the absolute truth." For this, the Prophet bestowed upon him the title "As-Siddiq" (The Truthful).\n\nDuring the dangerous migration (Hijrah) from Mecca to Medina, Abu Bakr accompanied the Prophet. When the enemy trackers stood right outside the Cave of Thawr, Abu Bakr feared for the Prophet\'s safety. The Prophet comforted him with words immortalized in the Quran: "Do not grieve; indeed Allah is with us."\n\nAbu Bakr\'s generosity knew no bounds. He spent nearly his entire fortune freeing persecuted slaves, including Bilal ibn Rabah. When the Prophet called for contributions for the Battle of Tabuk, Umar ibn al-Khattab brought half his wealth, thinking he would finally outdo Abu Bakr. But Abu Bakr arrived with his entire wealth. When the Prophet asked him what he had left for his family, Abu Bakr replied humbly, "I have left them Allah and His Messenger."\n\nFollowing the passing of the Prophet, when shock paralyzed the community, Abu Bakr stood steadfast and proclaimed: "Whoever worshipped Muhammad, know that Muhammad has passed away. But whoever worships Allah, know that Allah is Ever-Living and never dies." As the first Caliph, he united the Ummah, preserved the Quran into a single compiled Mushaf, and governed with unmatched humility and justice.'
  },
  {
    id: 'sahabah-umar',
    title: 'Umar ibn Al-Khattab: The Voice of Justice',
    subtitle: 'Al-Faruq, the leader who walked the streets at night to care for the needy.',
    category: 'Sahabah',
    readTime: '12 min',
    content: 'Umar ibn Al-Khattab (may Allah be pleased with him), known as Al-Faruq (The Criterion between Truth and Falsehood), was a man of extraordinary strength, justice, and devotion. Before Islam, he was a fierce opponent of the Muslims, but upon hearing the recitation of Surah Taha in his sister\'s house, his heart was completely transformed by the beauty and power of the Quran.\n\nHis acceptance of Islam brought immense dignity and strength to the early believers, who were finally able to pray publicly at the Kaaba. When the Prophet passed away and Abu Bakr completed his caliphate, Umar became the second Caliph of Islam. Under his leadership, the Islamic state expanded vastly, but Umar\'s personal life remained a model of absolute austerity and asceticism.\n\nUmar would disguise himself at night to patrol the dark streets of Medina, checking if any orphan, widow, or traveler was suffering. In one famous incident, he discovered a mother boiling stones in water to soothe her starving children to sleep. Weeping with remorse, Umar rushed to the public treasury, loaded a sack of flour and ghee onto his own back, and brought it to cook food with his own hands for the children.\n\nHis sense of accountability before Allah was terrifying to his own soul. He famously said: "If a stray mule stumbles on the banks of the Euphrates, I fear Allah will ask Umar why he did not pave the road for it." Umar established the Islamic Hijri calendar, regularized the Night Prayers (Taraweeh) in congregation, established social welfare stipends, and set the gold standard for honest governance.'
  },
  {
    id: 'sahabah-uthman',
    title: 'Uthman ibn Affan: Possessor of Two Lights',
    subtitle: 'The epitome of modesty, selflessness, and generous philanthropy.',
    category: 'Sahabah',
    readTime: '10 min',
    content: 'Uthman ibn Affan (may Allah be pleased with him) was blessed with the title "Dhun-Nurayn" (Possessor of Two Lights) because he married two of the Prophet\'s daughters, Ruqayyah and later Umm Kulthum. Known for his profound modesty and gentle character, the Prophet Muhammad (PBUH) once said: "Shall I not feel shy before a man whom even the angels feel shy before?"\n\nUthman was a wealthy and successful merchant, but his heart was entirely detached from worldly riches. When the Muslim immigrants arrived in Medina, clean drinking water was scarce and controlled by a merchant who sold water from the Well of Rumah at high prices. Uthman purchased the well for a massive sum and dedicated it as an open, free endowment (Waqf) for all people forever.\n\nDuring the preparation for the expedition of Tabuk (the Army of Hardship), Uthman financed one-third of the entire army, providing hundreds of camels loaded with supplies and thousands of gold coins. The Prophet was so moved that he declared: "Nothing Uthman does after today can harm him."\n\nDuring his caliphate as the third Caliph, Uthman oversaw the standardization and compilation of the Quran into the official Uthmani script, sending verified copies across the expanding Islamic empire. This monumental achievement preserved the recitation of the Quran for all generations to come.'
  },
  {
    id: 'sahabah-ali',
    title: 'Ali ibn Abi Talib: The Lion of Allah',
    subtitle: 'The courageous youth, gateway of knowledge, and fourth Righteous Caliph.',
    category: 'Sahabah',
    readTime: '11 min',
    content: 'Ali ibn Abi Talib (may Allah be pleased with him) was the cousin and son-in-law of Prophet Muhammad (peace be upon him), having married his beloved daughter Fatimah. Ali grew up directly under the guardianship of the Prophet and was the first child to embrace Islam at the tender age of ten.\n\nAli\'s courage was legendary. On the fateful night of the Prophet\'s migration, when Quraysh assassins surrounded the house to murder the Prophet, Ali willingly slept in the Prophet\'s bed as a decoy, risking his life so the Prophet could slip away safely. He stayed behind in Mecca for three days to return all trust deposits (Amanat) to their owners, even those who were enemies of Islam.\n\nOn the battlefield, Ali was an unstoppable warrior of justice, renowned as "Asadullah" (The Lion of Allah). At the fortress of Khaybar, when previous attempts had stalled, the Prophet announced: "Tomorrow I will give the banner to a man who loves Allah and His Messenger, and whom Allah and His Messenger love." The next morning, Ali received the banner, breached the formidable gates, and led the Muslims to a decisive victory.\n\nBeyond his martial prowess, Ali was an ocean of deep Quranic understanding, eloquence, and judicial wisdom. The Prophet said: "I am the city of knowledge, and Ali is its gate." As the fourth Caliph, Ali championed the rights of the poor and weak, living in the utmost simplicity and leaving behind a legacy of profound philosophical and spiritual wisdom.'
  },
  {
    id: 'sahabah-khadijah',
    title: 'Khadijah bint Khuwaylid: The Mother of Believers',
    subtitle: 'The noble businesswoman who stood by the Prophet with unwavering love.',
    category: 'Sahabah',
    readTime: '9 min',
    content: 'Khadijah bint Khuwaylid (may Allah be pleased with her) was a noble, intelligent, and highly respected businesswoman in Mecca, known even before Islam as "At-Tahirah" (The Pure One). Recognizing the exceptional honesty, trustworthiness, and good character of Muhammad (PBUH), she proposed marriage to him.\n\nWhen the first revelation descended upon the Prophet in the Cave of Hira and he returned home trembling with awe, it was Khadijah who comforted him with iconic words of solace: "Never! By Allah, Allah will never disgrace you. You keep good relations with your kith and kin, help the poor, serve your guests generously, and assist those afflicted by calamity."\n\nKhadijah was the very first person on earth to believe in Allah and the prophethood of Muhammad. For 25 years, she was his sole wife, best friend, and greatest support. She poured her vast wealth into supporting the persecuted early Muslims and endured the grueling three-year social and economic boycott in the valley of Shi\'b Abi Talib without a single word of complaint.\n\nSo beloved was she that the Angel Jibril once came to the Prophet saying: "O Messenger of Allah, here is Khadijah coming with food. When she arrives, convey to her greetings of peace from her Lord and from me, and give her the glad tidings of a palace of pearls in Paradise, wherein there will be neither noise nor fatigue." Her passing left such a deep void that the year was remembered as the "Year of Sorrow" (Am al-Huzn).'
  },
  {
    id: 'sahabah-khalid',
    title: 'Khalid ibn Al-Walid: The Sword of Allah',
    subtitle: 'The undefeated military genius who fought solely for the pleasure of Allah.',
    category: 'Sahabah',
    readTime: '10 min',
    content: 'Khalid ibn Al-Walid (may Allah be pleased with him) was one of the greatest military strategists in world history, never losing a single battle in his entire life across over a hundred engagements. When he embraced Islam in the 7th year of Hijrah, the Prophet Muhammad (peace be upon him) honored him with the noble title "Sayfullah" (The Unsheathed Sword of Allah).\n\nAt the Battle of Mut\'ah, when all three appointed commanders were martyred in succession against a massive Byzantine army, Khalid took the command banner. With brilliant night-time reorganizations and tactical maneuvers, he held off the enemy and led the vastly outnumbered Muslim forces back safely without panic, breaking nine swords in his hand during the battle.\n\nUnder Caliph Abu Bakr and Umar, Khalid led campaigns that liberated Iraq and the Levant from oppressive empires, culminating in the historic victory at the Battle of Yarmouk. Yet, Khalid\'s true greatness was not in his military victories, but in his absolute sincerity to Allah.\n\nWhen Caliph Umar issued an order relieving Khalid of supreme command to appoint Abu Ubaidah—to remind the people that victory comes only from Allah, not from any individual—Khalid accepted the decision immediately without the slightest resentment. He continued fighting in the front ranks as a humble soldier, saying: "I do not fight for the sake of Umar, I fight for the Lord of Umar." He passed away in his bed, expressing regret that he could not achieve martyrdom on the battlefield, yet earning the reward of one who gave everything for the truth.'
  },
  {
    id: 'prophet-dawud',
    title: 'Prophet Dawud: The Singing King',
    subtitle: 'The blessed prophet endowed with the Zabur, justice, and sweet praises.',
    category: 'Prophets',
    readTime: '9 min',
    content: 'Prophet Dawud (David, peace be upon him) was chosen by Allah as both a mighty king and a noble messenger to the Children of Israel. Allah revealed to him the sacred scripture of the Zabur (Psalms) and blessed him with one of the most melodious and captivating voices ever granted to a human being.\n\nWhen Dawud recited the praises of Allah, the mountains and flocks of wild birds would gather around him and chant the glorifications in unison. Allah also softened iron for Dawud like clay in his hands, allowing him to craft interlocking chainmail armor without heating it in fire, teaching him an honest trade so he could eat from the labor of his own hands.\n\nDespite ruling a vast and prosperous kingdom, Dawud was dedicated to relentless worship. The Prophet Muhammad (PBUH) praised him, saying: "The most beloved fasting to Allah is that of Dawud; he would fast every other day. And the most beloved prayer to Allah is that of Dawud; he would sleep half the night, pray for a third of it, and sleep for the remaining sixth."\n\nDawud was renowned for his fairness in arbitration and judgment. Once, two disputants presented a case about sheep entering a vineyard at night; Dawud listened with care, and his son Sulaiman suggested an even wiser resolution. Dawud\'s life is a masterclass in balancing worldly authority with deep spiritual devotion and humble manual work.'
  },
  {
    id: 'prophet-hud',
    title: 'Prophet Hud and the Giant Tribe of \'Ad',
    subtitle: 'The fall of the mighty civilization of Iram of the Pillars.',
    category: 'Prophets',
    readTime: '8 min',
    content: 'Prophet Hud (peace be upon him) was sent to the ancient tribe of \'Ad, who inhabited the sandy hills of Al-Ahqaf in southern Arabia. The people of \'Ad were blessed with unmatched physical stature, immense strength, and great architectural prowess. They built the magnificent city of Iram with lofty pillars, unmatched anywhere in the world.\n\nHowever, their physical strength fueled extreme arrogance. They began worshipping stone idols and terrorized neighboring tribes, boasting: "Who is greater than us in strength?" They built opulent palaces on every high hill merely for show and amusement.\n\nProphet Hud warned them with gentleness and sincere concern: "O my people, worship Allah; you have no deity other than Him. Will you not fear Him?" He reminded them that their strength, water springs, gardens, and cattle were all gifts from Allah, which could easily be taken away. The proud leaders mocked Hud, calling him foolish and a liar.\n\nWhen their defiance persisted, Allah withheld rain from them for three long years. Desperate, they saw a massive dark cloud spreading across the horizon and rejoiced, thinking it was bringing rain. But Hud told them: "No, this is what you sought to hasten—a wind containing a painful punishment."\n\nA ferocious, freezing hurricane struck \'Ad for seven nights and eight continuous days, tearing people from their feet like uprooted date palm trunks. The entire civilization was obliterated, while Hud and the believers were saved by Allah\'s mercy.'
  },
  {
    id: 'prophet-zakariya-yahya',
    title: 'Prophet Zakariya and Prophet Yahya',
    subtitle: 'The miracle of prayer answered in old age and the pure servant Yahya.',
    category: 'Prophets',
    readTime: '9 min',
    content: 'Prophet Zakariya (Zechariah, peace be upon him) was a devoted priest and prophet of the Children of Israel who had reached extreme old age with grey hair and frail bones. His wife was barren, and he had no children to carry forward the spiritual legacy and knowledge of the family of Yaqub.\n\nWhile caring for the pious Maryam in the temple sanctuary, Zakariya witnessed out-of-season fresh fruits placed before her miraculously by Allah. This ignited profound hope in his heart: the One who provides fruits without cause can surely grant a child beyond natural means.\n\nZakariya retreated into private prayer, calling upon his Lord in a secret, tender voice: "My Lord, indeed my bones have grown feeble, and my head has filled with white, and never have I been in my supplication to You, my Lord, unhappy... So grant me from Yourself an heir who will inherit me and inherit from the family of Jacob."\n\nWhile standing in prayer in the chamber, the angels called out to him: "Allah gives you glad tidings of Yahya (John), confirming a word from Allah, honorable, chaste, and a prophet from among the righteous." Amazed, Zakariya asked for a sign, and Allah made him unable to speak to people for three days except through gestures, while his tongue remained free to glorify Allah.\n\nYahya grew up to be exceptionally compassionate, wise as a youth, deeply gentle to animals and people, and free from arrogance. Father and son dedicated their entire lives to serving the truth, teaching humanity that no prayer is ever impossible for Allah.'
  },
  {
    id: 'parable-three-in-cave',
    title: 'The Three Men Trapped in the Cave',
    subtitle: 'A miraculous escape through the virtue of sincere deeds done for Allah alone.',
    category: 'Islamic Wisdom',
    readTime: '8 min',
    content: 'The Prophet Muhammad (peace be upon him) narrated a profound story of three men from previous nations who were traveling together when a severe storm forced them to seek shelter inside a mountain cave. Suddenly, a massive boulder broke loose from the cliff and crashed down, completely sealing the mouth of the cave. Trapped in pitch darkness with no hope of human rescue, they realized that only their sincere deeds done purely for Allah\'s sake could save them.\n\nThe first man prayed: "O Allah, I had elderly parents whom I served fresh milk every evening before my own children. One night I was delayed, and by the time I returned, my parents were asleep. I stood by their heads holding the milk bowl throughout the night until dawn, refusing to disturb them or feed my hungry children until they drank first. O Allah, if I did this seeking solely Your pleasure, relieve us from this distress." The giant boulder shifted slightly, letting in a beam of light, but not enough to escape.\n\nThe second man prayed: "O Allah, I fell passionately in love with my cousin and tried to seduce her, but she refused. In a time of extreme poverty, she came to me for help. I offered her 120 gold coins on the condition that she submit to me. When we were alone and I was about to commit the sin, she cried: \'Fear Allah, and do not break the seal unlawfully.\' Shaken by the fear of You, I stood up and left her with the gold. O Allah, if I abandoned that sin solely out of fear of You, relieve our distress." The boulder moved further, but the opening was still too narrow.\n\nThe third man prayed: "O Allah, I hired laborers to work for me, and all took their wages except one man who left his pay. I invested his wages into cattle, which multiplied into a vast herd. Years later, the laborer returned and asked for his wage. I told him: \'All these cows and shepherds belong to you.\' Thinking I was joking, he was astonished when I gave him every single animal without taking a penny. O Allah, if I did this seeking Your Countenance, open this rock for us."\n\nThe rock rolled completely away, and all three men walked out into the sunshine rejoicing in the mercy of Allah.'
  },
  {
    id: 'parable-99-murders',
    title: 'The Man Who Killed 99 People',
    subtitle: 'A timeless lesson on the boundless, all-encompassing mercy of Allah.',
    category: 'Islamic Wisdom',
    readTime: '7 min',
    content: 'The Prophet Muhammad (peace be upon him) told the story of a man from the Children of Israel who had lived a life of heinous crime, having murdered ninety-nine innocent people. Eventually, a spark of conscience awoke within him, and he desperately sought to know if there was any chance of forgiveness for his soul.\n\nHe sought out a devout worshipper (hermit) and asked: "I have killed ninety-nine people. Is there any repentance for me?" The worshipper, lacking deep knowledge and underestimating Allah\'s mercy, replied: "No, there is no repentance for you." In despair and rage, the man killed the worshipper as well, completing a count of one hundred murders.\n\nStill searching for redemption, he asked the people for the most knowledgeable scholar on earth. When he found the scholar, he asked: "I have killed a hundred people. Can I still repent?" The wise scholar answered: "Yes! Who can stand between you and repentance? But you must leave your wicked town because it is a land of evil, and migrate to a righteous town where people worship Allah alone, and join them in their worship."\n\nThe man set out immediately with a sincere, remorseful heart. Halfway between the two towns, the angel of death came to take his soul. As he fell dying, he leaned with his chest towards the town of the righteous.\n\nA dispute arose between the Angels of Mercy and the Angels of Punishment. The Angels of Mercy said: "He came repenting with his heart turned toward Allah." The Angels of Punishment argued: "He never performed a single good deed in his life."\n\nAllah sent an angel in human form to judge between them, saying: "Measure the distance between the two lands; whichever land he is closer to, he belongs to its people." When they measured, Allah caused the righteous land to draw closer to him by a handspan. The Angels of Mercy took his soul, and he was forgiven. This story is an eternal beacon of hope that no sin is greater than Allah\'s infinite mercy when met with sincere repentance.'
  },
  {
    id: 'parable-thirsty-dog',
    title: 'The Thirsty Dog and the Well',
    subtitle: 'How an act of sincere compassion to an animal wiped away a lifetime of sins.',
    category: 'Islamic Wisdom',
    readTime: '5 min',
    content: 'The Prophet Muhammad (peace be upon him) shared a touching narrative of a man who was walking on a long, scorching desert journey. As the intense heat beat down upon him, he was overcome with severe thirst. Searching around, he found a deep well. He climbed down into the well, drank his fill of fresh water, and climbed back out refreshed.\n\nAs he reached the top, he saw a dog panting heavily, licking the damp desert mud in extreme agony from thirst. The man felt deep empathy in his heart and said to himself: "This poor creature is suffering from thirst just as I was moments ago."\n\nBecause the well had no bucket or rope, the man climbed back down into the deep well. He removed his leather shoe (Khuff), filled it to the brim with water, and held it carefully between his teeth so he could use both hands to climb back up. Reaching the surface, he placed the shoe before the dying dog and allowed it to drink until its thirst was quenched.\n\nAllah was so pleased with this pure act of selfless compassion that He appreciated the man\'s deed, forgave all of his past sins, and admitted him into Paradise.\n\nWhen the Companions heard this, they asked with wonder: "O Messenger of Allah, is there a reward for us in serving animals?" The Prophet replied with a timeless golden rule of Islamic ethics: "In every living being with a moist liver (every living creature), there is a reward for charity."'
  }
];
