export const STORIES = [
  {
    id: '1',
    title: 'The Story of Prophet Musa',
    subtitle: 'A tale of patience, faith, and standing up to tyranny.',
    category: 'Prophets',
    readTime: '10 min',
    content: 'Prophet Musa (Moses) is one of the most frequently mentioned prophets in the Quran. His story is a profound narrative of standing against the tyranny of the Pharaoh (Fir\'aun), leading the Children of Israel out of bondage, and receiving the Divine revelation on Mount Sinai.\n\nMusa was born during a time when Pharaoh had ordered the killing of all newborn boys among the Israelites. His mother, guided by Allah, placed him in a basket and set it adrift on the Nile. Miraculously, he was found and adopted by Pharaoh\'s own family. Growing up in the palace, Musa witnessed the oppression of his people.\n\nAfter accidentally killing an Egyptian taskmaster, Musa fled to Midian, where he married and worked as a shepherd. Years later, on his way back to Egypt, he saw a burning bush on Mount Tur. There, Allah spoke to him, appointing him as a messenger and giving him miracles—his staff turning into a serpent and his hand shining white.\n\nMusa confronted Pharaoh, demanding the release of the Israelites. Despite witnessing the miracles and the subsequent plagues, Pharaoh remained arrogant. Eventually, Musa led his people out of Egypt. Trapped between Pharaoh\'s pursuing army and the Red Sea, Musa struck the water with his staff, parting it to allow the Israelites to cross safely. When Pharaoh and his army tried to follow, the sea crashed down, drowning them.\n\nThe story of Musa is a powerful reminder that no matter how powerful a tyrant may seem, Allah\'s will always prevails, and He is always with the oppressed who maintain their faith.',
  },
  {
    id: '2',
    title: 'Companions of the Cave',
    subtitle: 'The youth who sought refuge in the cave to protect their faith.',
    category: 'Quranic Tales',
    readTime: '7 min',
    content: 'The story of the Companions of the Cave (Ashab al-Kahf) is narrated in Surah Al-Kahf. It is a beautiful story about a group of righteous youth who lived in a city ruled by a tyrannical king who forced his people to worship idols.\n\nRejecting the polytheism of their society, these young men secretly believed in the Oneness of Allah. When their faith was discovered, they faced persecution and possible death. To protect their religion, they fled the city and took refuge in a secluded cave, accompanied by their loyal dog.\n\nIn the cave, they prayed to Allah for mercy and guidance. Allah answered their prayers by placing them into a deep sleep that lasted for over 300 years. During this time, the world outside changed drastically; the tyrannical ruler was gone, and the city had embraced monotheism.\n\nWhen they awoke, they thought they had only slept for a day or part of a day. They sent one of their companions to the city with an old coin to buy food, warning him to be cautious. The shopkeeper, seeing the ancient coin, was astonished, and the secret of the sleepers was revealed to the city.\n\nThe people rejoiced at witnessing this miracle of resurrection and the preservation of faith. The Companions of the Cave soon passed away naturally, and a place of worship was built over their cave. Their story stands as an eternal testament to Allah\'s power to protect those who rely on Him and the reality of life after death.'
  },
  {
    id: '3',
    title: 'The Story of Prophet Nuh',
    subtitle: 'The steadfastness of a prophet over 950 years of preaching.',
    category: 'Prophets',
    readTime: '12 min',
    content: 'Prophet Nuh (Noah) is revered as one of the first major messengers sent by Allah to guide humanity back to monotheism. His people had fallen into idol worship, creating deities out of righteous men who had lived before them.\n\nFor 950 years, Nuh patiently called his people to worship Allah alone. He preached to them day and night, in public and in private. He warned them of the consequences of their disbelief and reminded them of Allah\'s blessings. However, his people mocked him, rejected his message, and only a small group of the poor and weak believed in him.\n\nEventually, Allah revealed to Nuh that no more of his people would believe. He was commanded to build a massive ark (ship) under Divine guidance. As he built the ark on dry land, the chiefs of his people passed by and ridiculed him, calling him a madman.\n\nWhen the command of Allah came, water gushed forth from the earth, and rain poured from the skies. Nuh gathered the believers and a pair of every animal onto the ark. The floodwaters rose, covering the highest mountains. Even Nuh\'s own son, who had disbelieved, drowned, refusing to board the ark and vainly seeking refuge on a mountain.\n\nThe ark sailed safely over the devastating waves until the waters subsided, and it came to rest on Mount Judi. Nuh and the believers disembarked, establishing a new beginning for humanity. His story is a profound lesson in patience, perseverance, and the ultimate justice of Allah.'
  },
  {
    id: '4',
    title: 'Salman al-Farsi',
    subtitle: 'The search for truth across different lands and religions.',
    category: 'Sahabah',
    readTime: '8 min',
    content: 'Salman al-Farsi was a companion of the Prophet Muhammad (PBUH) known for his incredible journey in search of the true religion. Born in Persia (modern-day Iran) to a wealthy Zoroastrian family, Salman was deeply devoted to the sacred fire, tending to it so it would never extinguish.\n\nHowever, his spiritual thirst was not quenched. After encountering a group of Christians praying in a church, he was captivated by their worship. Leaving his privileged life behind, he traveled to Syria to learn from Christian monks. As each monk approached death, Salman would ask for guidance, and he was continually directed to the next righteous scholar.\n\nEventually, the last monk told him that the time for a new prophet was near, one who would appear in the land of Arabia, marked by a land of date palms, and possessing specific signs of prophethood.\n\nSalman journeyed towards Arabia but was betrayed and sold into slavery in Medina. When the Prophet Muhammad (PBUH) migrated to Medina, Salman recognized the signs: the Prophet accepted gifts but not charity, and he bore the Seal of Prophethood on his back.\n\nSalman embraced Islam and played a crucial role in the Muslim community. He is famously known for suggesting the strategy of digging a trench (Khandaq) around Medina to defend against the coalition of enemy forces, a Persian military tactic previously unknown to the Arabs. Salman\'s life is a testament to the sincere and relentless pursuit of truth.'
  },
  {
    id: '5',
    title: 'The Story of Prophet Yusuf',
    subtitle: 'A beautiful narrative of betrayal, patience, and ultimate triumph.',
    category: 'Prophets',
    readTime: '15 min',
    content: 'Prophet Yusuf (Joseph) is the protagonist of Surah Yusuf, which the Quran calls "the best of stories." He was the beloved son of Prophet Yaqub (Jacob). Yusuf\'s ten older half-brothers grew intensely jealous of him, plotting to eliminate him.\n\nThey threw him into a dry well and told their father that a wolf had devoured him, showing a blood-stained shirt as false proof. Yaqub, though heartbroken, responded with beautiful patience (Sabr Jameel). Yusuf was rescued by a passing caravan and sold into slavery in Egypt to a high-ranking minister.\n\nGrowing up into a strikingly handsome and wise young man, Yusuf faced a new trial when the minister\'s wife tried to seduce him. Preferring prison over sin, Yusuf prayed to Allah for protection and was unjustly imprisoned.\n\nIn prison, Allah granted him the ability to interpret dreams. Years later, the King of Egypt had a disturbing dream about seven fat cows being eaten by seven lean ones, and seven green ears of corn and seven dry ones. None could interpret it until Yusuf explained that Egypt would face seven years of abundance followed by seven years of severe famine. He advised them to store the surplus grain.\n\nImpressed by his wisdom, the King exonerated Yusuf and appointed him as the chief minister over the storehouses. When the famine struck, Yusuf\'s brothers came to Egypt seeking grain, not recognizing him. After a series of tests to bring his younger full-brother Binyamin to him, Yusuf finally revealed his identity, forgiving them completely.\n\nThe family was reunited in Egypt, fulfilling Yusuf\'s childhood dream where the sun, the moon, and eleven stars prostrated to him. His story beautifully illustrates that no matter how deep the well or dark the prison, Allah\'s plan is flawless and leads to the ultimate triumph of the righteous.'
  },
  {
    id: '6',
    title: 'Bilal ibn Rabah',
    subtitle: 'From a persecuted slave to the first Muezzin of Islam.',
    category: 'Sahabah',
    readTime: '6 min',
    content: 'Bilal ibn Rabah was an Abyssinian slave living in Mecca when the message of Islam was first preached. Despite the immense danger, Bilal embraced Islam, deeply resonating with its message of equality and the Oneness of Allah.\n\nWhen his master, Umayya ibn Khalaf, discovered Bilal\'s conversion, he subjected him to brutal torture. In the scorching heat of the Arabian desert, Umayya would pin Bilal to the ground and place a massive, burning boulder on his chest, demanding he renounce Islam and worship the idols. But Bilal\'s faith was unshakable. He continuously repeated "Ahad, Ahad" (One, One), affirming his belief in the one true God.\n\nHis remarkable endurance caught the attention of Abu Bakr, a close companion of the Prophet Muhammad (PBUH), who bought Bilal and set him free.\n\nWhen the Muslims migrated to Medina and the call to prayer (Adhan) was instituted, the Prophet chose Bilal to be the first Muezzin of Islam. His deep, melodious voice echoed across Medina, calling the faithful to prayer. Following the conquest of Mecca, it was Bilal who climbed atop the Kaaba to declare the Adhan, symbolizing the ultimate victory of truth over ignorance.\n\nBilal\'s story is a profound symbol of endurance, the equalizing power of Islam, and how true nobility is defined by piety, not race or social status.'
  }
];
