export const SURAH_DATA = [
  { "number": 1, "arabic_name": "الفاتحة", "transliteration": "Al-Fatihah", "english_translation": "The Opening", "ayah_count": 7, "revelation": "Meccan" },
  { "number": 2, "arabic_name": "البقرة", "transliteration": "Al-Baqarah", "english_translation": "The Cow", "ayah_count": 286, "revelation": "Medinan" },
  { "number": 3, "arabic_name": "آل عمران", "transliteration": "Ali 'Imran", "english_translation": "The Family of Imran", "ayah_count": 200, "revelation": "Medinan" },
  { "number": 4, "arabic_name": "النساء", "transliteration": "An-Nisa", "english_translation": "The Women", "ayah_count": 176, "revelation": "Medinan" },
  { "number": 5, "arabic_name": "المائدة", "transliteration": "Al-Ma'idah", "english_translation": "The Table Spread", "ayah_count": 120, "revelation": "Medinan" },
  { "number": 6, "arabic_name": "الأنعام", "transliteration": "Al-An'am", "english_translation": "The Cattle", "ayah_count": 165, "revelation": "Meccan" },
  { "number": 7, "arabic_name": "الأعراف", "transliteration": "Al-A'raf", "english_translation": "The Heights", "ayah_count": 206, "revelation": "Meccan" },
  { "number": 8, "arabic_name": "الأنفال", "transliteration": "Al-Anfal", "english_translation": "The Spoils of War", "ayah_count": 75, "revelation": "Medinan" },
  { "number": 9, "arabic_name": "التوبة", "transliteration": "At-Tawbah", "english_translation": "The Repentance", "ayah_count": 129, "revelation": "Medinan" },
  { "number": 10, "arabic_name": "يونس", "transliteration": "Yunus", "english_translation": "Jonah", "ayah_count": 109, "revelation": "Meccan" },
  { "number": 11, "arabic_name": "هود", "transliteration": "Hud", "english_translation": "Hud", "ayah_count": 123, "revelation": "Meccan" },
  { "number": 12, "arabic_name": "يوسف", "transliteration": "Yusuf", "english_translation": "Joseph", "ayah_count": 111, "revelation": "Meccan" },
  { "number": 13, "arabic_name": "الرعد", "transliteration": "Ar-Ra'd", "english_translation": "The Thunder", "ayah_count": 43, "revelation": "Medinan" },
  { "number": 14, "arabic_name": "ابراهيم", "transliteration": "Ibrahim", "english_translation": "Abraham", "ayah_count": 52, "revelation": "Meccan" },
  { "number": 15, "arabic_name": "الحجر", "transliteration": "Al-Hijr", "english_translation": "The Rocky Tract", "ayah_count": 99, "revelation": "Meccan" },
  { "number": 16, "arabic_name": "النحل", "transliteration": "An-Nahl", "english_translation": "The Bee", "ayah_count": 128, "revelation": "Meccan" },
  { "number": 17, "arabic_name": "الإسراء", "transliteration": "Al-Isra", "english_translation": "The Night Journey", "ayah_count": 111, "revelation": "Meccan" },
  { "number": 18, "arabic_name": "الكهف", "transliteration": "Al-Kahf", "english_translation": "The Cave", "ayah_count": 110, "revelation": "Meccan" },
  { "number": 19, "arabic_name": "مريم", "transliteration": "Maryam", "english_translation": "Mary", "ayah_count": 98, "revelation": "Meccan" },
  { "number": 20, "arabic_name": "طه", "transliteration": "Ta-Ha", "english_translation": "Ta-Ha", "ayah_count": 135, "revelation": "Meccan" },
  { "number": 21, "arabic_name": "الأنبياء", "transliteration": "Al-Anbiya", "english_translation": "The Prophets", "ayah_count": 112, "revelation": "Meccan" },
  { "number": 22, "arabic_name": "الحج", "transliteration": "Al-Hajj", "english_translation": "The Pilgrimage", "ayah_count": 78, "revelation": "Medinan" },
  { "number": 23, "arabic_name": "المؤمنون", "transliteration": "Al-Mu'minun", "english_translation": "The Believers", "ayah_count": 118, "revelation": "Meccan" },
  { "number": 24, "arabic_name": "النور", "transliteration": "An-Nur", "english_translation": "The Light", "ayah_count": 64, "revelation": "Medinan" },
  { "number": 25, "arabic_name": "الفرقان", "transliteration": "Al-Furqan", "english_translation": "The Criterion", "ayah_count": 77, "revelation": "Meccan" },
  { "number": 26, "arabic_name": "الشعراء", "transliteration": "Ash-Shu'ara", "english_translation": "The Poets", "ayah_count": 227, "revelation": "Meccan" },
  { "number": 27, "arabic_name": "النمل", "transliteration": "An-Naml", "english_translation": "The Ant", "ayah_count": 93, "revelation": "Meccan" },
  { "number": 28, "arabic_name": "القصص", "transliteration": "Al-Qasas", "english_translation": "The Narrative", "ayah_count": 88, "revelation": "Meccan" },
  { "number": 29, "arabic_name": "العنكبوت", "transliteration": "Al-'Ankabut", "english_translation": "The Spider", "ayah_count": 69, "revelation": "Meccan" },
  { "number": 30, "arabic_name": "الروم", "transliteration": "Ar-Rum", "english_translation": "The Romans", "ayah_count": 60, "revelation": "Meccan" },
  { "number": 31, "arabic_name": "لقمان", "transliteration": "Luqman", "english_translation": "Luqman", "ayah_count": 34, "revelation": "Meccan" },
  { "number": 32, "arabic_name": "السجدة", "transliteration": "As-Sajdah", "english_translation": "The Prostration", "ayah_count": 30, "revelation": "Meccan" },
  { "number": 33, "arabic_name": "الأحزاب", "transliteration": "Al-Ahzab", "english_translation": "The Allies", "ayah_count": 73, "revelation": "Medinan" },
  { "number": 34, "arabic_name": "سبأ", "transliteration": "Saba", "english_translation": "Sheba", "ayah_count": 54, "revelation": "Meccan" },
  { "number": 35, "arabic_name": "فاطر", "transliteration": "Fatir", "english_translation": "The Originator", "ayah_count": 45, "revelation": "Meccan" },
  { "number": 36, "arabic_name": "يس", "transliteration": "Ya-Sin", "english_translation": "Ya-Sin", "ayah_count": 83, "revelation": "Meccan" },
  { "number": 37, "arabic_name": "الصافات", "transliteration": "As-Saffat", "english_translation": "Those Who Set The Ranks", "ayah_count": 182, "revelation": "Meccan" },
  { "number": 38, "arabic_name": "ص", "transliteration": "Sad", "english_translation": "Sad", "ayah_count": 88, "revelation": "Meccan" },
  { "number": 39, "arabic_name": "الزمر", "transliteration": "Az-Zumar", "english_translation": "The Companies", "ayah_count": 75, "revelation": "Meccan" },
  { "number": 40, "arabic_name": "غافر", "transliteration": "Ghafir", "english_translation": "The Forgiver", "ayah_count": 85, "revelation": "Meccan" },
  { "number": 41, "arabic_name": "فصلت", "transliteration": "Fussilat", "english_translation": "Explained in Detail", "ayah_count": 54, "revelation": "Meccan" },
  { "number": 42, "arabic_name": "الشورى", "transliteration": "Ash-Shura", "english_translation": "Consultation", "ayah_count": 53, "revelation": "Meccan" },
  { "number": 43, "arabic_name": "الزخرف", "transliteration": "Az-Zukhruf", "english_translation": "The Ornaments of Gold", "ayah_count": 89, "revelation": "Meccan" },
  { "number": 44, "arabic_name": "الدخان", "transliteration": "Ad-Dukhan", "english_translation": "The Smoke", "ayah_count": 59, "revelation": "Meccan" },
  { "number": 45, "arabic_name": "الجاثية", "transliteration": "Al-Jathiyah", "english_translation": "The Kneeling", "ayah_count": 37, "revelation": "Meccan" },
  { "number": 46, "arabic_name": "الأحقاف", "transliteration": "Al-Ahqaf", "english_translation": "The Wind-Curved Sandhills", "ayah_count": 35, "revelation": "Meccan" },
  { "number": 47, "arabic_name": "محمد", "transliteration": "Muhammad", "english_translation": "Muhammad", "ayah_count": 38, "revelation": "Medinan" },
  { "number": 48, "arabic_name": "الفتح", "transliteration": "Al-Fath", "english_translation": "The Victory", "ayah_count": 29, "revelation": "Medinan" },
  { "number": 49, "arabic_name": "الحجرات", "transliteration": "Al-Hujurat", "english_translation": "The Private Chambers", "ayah_count": 18, "revelation": "Medinan" },
  { "number": 50, "arabic_name": "ق", "transliteration": "Qaf", "english_translation": "Qaf", "ayah_count": 45, "revelation": "Meccan" },
  { "number": 51, "arabic_name": "الذاريات", "transliteration": "Ad-Dhariyat", "english_translation": "The Scattering Winds", "ayah_count": 60, "revelation": "Meccan" },
  { "number": 52, "arabic_name": "الطور", "transliteration": "At-Tur", "english_translation": "The Mount", "ayah_count": 49, "revelation": "Meccan" },
  { "number": 53, "arabic_name": "النجم", "transliteration": "An-Najm", "english_translation": "The Star", "ayah_count": 62, "revelation": "Meccan" },
  { "number": 54, "arabic_name": "القمر", "transliteration": "Al-Qamar", "english_translation": "The Moon", "ayah_count": 55, "revelation": "Meccan" },
  { "number": 55, "arabic_name": "الرحمن", "transliteration": "Ar-Rahman", "english_translation": "The Beneficent", "ayah_count": 78, "revelation": "Medinan" },
  { "number": 56, "arabic_name": "الواقعة", "transliteration": "Al-Waqi'ah", "english_translation": "The Inevitable", "ayah_count": 96, "revelation": "Meccan" },
  { "number": 57, "arabic_name": "الحديد", "transliteration": "Al-Hadid", "english_translation": "The Iron", "ayah_count": 29, "revelation": "Medinan" },
  { "number": 58, "arabic_name": "المجادلة", "transliteration": "Al-Mujadilah", "english_translation": "The Pleading Woman", "ayah_count": 22, "revelation": "Medinan" },
  { "number": 59, "arabic_name": "الحشر", "transliteration": "Al-Hashr", "english_translation": "The Exile", "ayah_count": 24, "revelation": "Medinan" },
  { "number": 60, "arabic_name": "الممتحنة", "transliteration": "Al-Mumtahanah", "english_translation": "She That Is To Be Examined", "ayah_count": 13, "revelation": "Medinan" },
  { "number": 61, "arabic_name": "الصف", "transliteration": "As-Saff", "english_translation": "The Ranks", "ayah_count": 14, "revelation": "Medinan" },
  { "number": 62, "arabic_name": "الجمعة", "transliteration": "Al-Jumu'ah", "english_translation": "The Congregation, Friday", "ayah_count": 11, "revelation": "Medinan" },
  { "number": 63, "arabic_name": "المنافقون", "transliteration": "Al-Munafiqun", "english_translation": "The Hypocrites", "ayah_count": 11, "revelation": "Medinan" },
  { "number": 64, "arabic_name": "التغابن", "transliteration": "At-Taghabun", "english_translation": "The Mutual Disillusion", "ayah_count": 18, "revelation": "Medinan" },
  { "number": 65, "arabic_name": "الطلاق", "transliteration": "At-Talaq", "english_translation": "The Divorce", "ayah_count": 12, "revelation": "Medinan" },
  { "number": 66, "arabic_name": "التحريم", "transliteration": "At-Tahrim", "english_translation": "The Prohibition", "ayah_count": 12, "revelation": "Medinan" },
  { "number": 67, "arabic_name": "الملك", "transliteration": "Al-Mulk", "english_translation": "The Sovereignty", "ayah_count": 30, "revelation": "Meccan" },
  { "number": 68, "arabic_name": "القلم", "transliteration": "Al-Qalam", "english_translation": "The Pen", "ayah_count": 52, "revelation": "Meccan" },
  { "number": 69, "arabic_name": "الحاقة", "transliteration": "Al-Haqqah", "english_translation": "The Reality", "ayah_count": 52, "revelation": "Meccan" },
  { "number": 70, "arabic_name": "المعارج", "transliteration": "Al-Ma'arij", "english_translation": "The Ascending Stairways", "ayah_count": 44, "revelation": "Meccan" },
  { "number": 71, "arabic_name": "نوح", "transliteration": "Nuh", "english_translation": "Noah", "ayah_count": 28, "revelation": "Meccan" },
  { "number": 72, "arabic_name": "الجن", "transliteration": "Al-Jinn", "english_translation": "The Jinn", "ayah_count": 28, "revelation": "Meccan" },
  { "number": 73, "arabic_name": "المزمل", "transliteration": "Al-Muzzammil", "english_translation": "The Enshrouded One", "ayah_count": 20, "revelation": "Meccan" },
  { "number": 74, "arabic_name": "المدثر", "transliteration": "Al-Muddaththir", "english_translation": "The Cloaked One", "ayah_count": 56, "revelation": "Meccan" },
  { "number": 75, "arabic_name": "القيامة", "transliteration": "Al-Qiyamah", "english_translation": "The Resurrection", "ayah_count": 40, "revelation": "Meccan" },
  { "number": 76, "arabic_name": "الانسان", "transliteration": "Al-Insan", "english_translation": "The Man", "ayah_count": 31, "revelation": "Medinan" },
  { "number": 77, "arabic_name": "المرسلات", "transliteration": "Al-Mursalat", "english_translation": "The Emissaries", "ayah_count": 50, "revelation": "Meccan" },
  { "number": 78, "arabic_name": "النبأ", "transliteration": "An-Naba", "english_translation": "The Tidings", "ayah_count": 40, "revelation": "Meccan" },
  { "number": 79, "arabic_name": "النازعات", "transliteration": "An-Nazi'at", "english_translation": "Those Who Drag Forth", "ayah_count": 46, "revelation": "Meccan" },
  { "number": 80, "arabic_name": "عبس", "transliteration": "Abasa", "english_translation": "He Frowned", "ayah_count": 42, "revelation": "Meccan" },
  { "number": 81, "arabic_name": "التكوير", "transliteration": "At-Takwir", "english_translation": "The Overthrowing", "ayah_count": 29, "revelation": "Meccan" },
  { "number": 82, "arabic_name": "الإنفطار", "transliteration": "Al-Infitar", "english_translation": "The Cleaving", "ayah_count": 19, "revelation": "Meccan" },
  { "number": 83, "arabic_name": "المطففين", "transliteration": "Al-Mutaffifin", "english_translation": "The Defrauding", "ayah_count": 36, "revelation": "Meccan" },
  { "number": 84, "arabic_name": "الإنشقاق", "transliteration": "Al-Inshiqaq", "english_translation": "The Sundering", "ayah_count": 25, "revelation": "Meccan" },
  { "number": 85, "arabic_name": "البروج", "transliteration": "Al-Buruj", "english_translation": "The Mansions of the Stars", "ayah_count": 22, "revelation": "Meccan" },
  { "number": 86, "arabic_name": "الطارق", "transliteration": "At-Tariq", "english_translation": "The Night-Comer", "ayah_count": 17, "revelation": "Meccan" },
  { "number": 87, "arabic_name": "الأعلى", "transliteration": "Al-A'la", "english_translation": "The Most High", "ayah_count": 19, "revelation": "Meccan" },
  { "number": 88, "arabic_name": "الغاشية", "transliteration": "Al-Ghashiyah", "english_translation": "The Overwhelming", "ayah_count": 26, "revelation": "Meccan" },
  { "number": 89, "arabic_name": "الفجر", "transliteration": "Al-Fajr", "english_translation": "The Dawn", "ayah_count": 30, "revelation": "Meccan" },
  { "number": 90, "arabic_name": "البلد", "transliteration": "Al-Balad", "english_translation": "The City", "ayah_count": 20, "revelation": "Meccan" },
  { "number": 91, "arabic_name": "الشمس", "transliteration": "Ash-Shams", "english_translation": "The Sun", "ayah_count": 15, "revelation": "Meccan" },
  { "number": 92, "arabic_name": "الليل", "transliteration": "Al-Lail", "english_translation": "The Night", "ayah_count": 21, "revelation": "Meccan" },
  { "number": 93, "arabic_name": "الضحى", "transliteration": "Ad-Duha", "english_translation": "The Morning Hours", "ayah_count": 11, "revelation": "Meccan" },
  { "number": 94, "arabic_name": "الشرح", "transliteration": "Ash-Sharh", "english_translation": "The Relief", "ayah_count": 8, "revelation": "Meccan" },
  { "number": 95, "arabic_name": "التين", "transliteration": "At-Tin", "english_translation": "The Fig", "ayah_count": 8, "revelation": "Meccan" },
  { "number": 96, "arabic_name": "العلق", "transliteration": "Al-'Alaq", "english_translation": "The Clot", "ayah_count": 19, "revelation": "Meccan" },
  { "number": 97, "arabic_name": "القدر", "transliteration": "Al-Qadr", "english_translation": "The Power, Fate", "ayah_count": 5, "revelation": "Meccan" },
  { "number": 98, "arabic_name": "البينة", "transliteration": "Al-Bayyinah", "english_translation": "The Evidence", "ayah_count": 8, "revelation": "Medinan" },
  { "number": 99, "arabic_name": "الزلزلة", "transliteration": "Az-Zalzalah", "english_translation": "The Earthquake", "ayah_count": 8, "revelation": "Medinan" },
  { "number": 100, "arabic_name": "العاديات", "transliteration": "Al-'Adiyat", "english_translation": "The Runners", "ayah_count": 11, "revelation": "Meccan" },
  { "number": 101, "arabic_name": "القارعة", "transliteration": "Al-Qari'ah", "english_translation": "The Calamity", "ayah_count": 11, "revelation": "Meccan" },
  { "number": 102, "arabic_name": "التكاثر", "transliteration": "At-Takathur", "english_translation": "The Competition", "ayah_count": 8, "revelation": "Meccan" },
  { "number": 103, "arabic_name": "العصر", "transliteration": "Al-'Asr", "english_translation": "The Declining Day, Time", "ayah_count": 3, "revelation": "Meccan" },
  { "number": 104, "arabic_name": "الهمزة", "transliteration": "Al-Humazah", "english_translation": "The Traducer", "ayah_count": 9, "revelation": "Meccan" },
  { "number": 105, "arabic_name": "الفيل", "transliteration": "Al-Fil", "english_translation": "The Elephant", "ayah_count": 5, "revelation": "Meccan" },
  { "number": 106, "arabic_name": "قريش", "transliteration": "Quraish", "english_translation": "Quraysh", "ayah_count": 4, "revelation": "Meccan" },
  { "number": 107, "arabic_name": "الماعون", "transliteration": "Al-Ma'un", "english_translation": "The Kindness", "ayah_count": 7, "revelation": "Meccan" },
  { "number": 108, "arabic_name": "الكوثر", "transliteration": "Al-Kawthar", "english_translation": "The Abundance", "ayah_count": 3, "revelation": "Meccan" },
  { "number": 109, "arabic_name": "الكافرون", "transliteration": "Al-Kafirun", "english_translation": "The Disbelievers", "ayah_count": 6, "revelation": "Meccan" },
  { "number": 110, "arabic_name": "النصر", "transliteration": "An-Nasr", "english_translation": "The Divine Support", "ayah_count": 3, "revelation": "Medinan" },
  { "number": 111, "arabic_name": "المسد", "transliteration": "Al-Masad", "english_translation": "The Palm Fiber", "ayah_count": 5, "revelation": "Meccan" },
  { "number": 112, "arabic_name": "الإخلاص", "transliteration": "Al-Ikhlas", "english_translation": "The Sincerity", "ayah_count": 4, "revelation": "Meccan" },
  { "number": 113, "arabic_name": "الفلق", "transliteration": "Al-Falaq", "english_translation": "The Daybreak", "ayah_count": 5, "revelation": "Meccan" },
  { "number": 114, "arabic_name": "الناس", "transliteration": "An-Nas", "english_translation": "Mankind", "ayah_count": 6, "revelation": "Meccan" }
];
